### ISSUE TITLE
MIN_DOCKER_VERSION

### ISSUE THREAD

**Issue by burtsevyg** [oracle/docker-images#1012]
in docker-images/OracleDatabase/SingleInstance/dockerfiles/buildDockerImage.sh
set
MIN_DOCKER_VERSION="17.09"
that is very bad for me because:
rhel docker version 1.13.1

**Comment by Djelibeybi** [comment]
We require at least 17.09 because the single-instance Database image uses a multi-stage build with permission change on copy. That functionality is not available in such an old version of Docker. You will need to upgrade Docker to a more up-to-date version in order to build the image.

However, you don't need to use an updated version to run a container from the image.

So, you could install Oracle Linux 7 and install our build of Docker 18.03 to build the image and then deploy it onto whatever machine you like.

**Comment by burtsevyg** [comment]
> We require at least 17.09 because the single-instance Database image uses a multi-stage build
It is not true. Only health check failed when I change MIN_DOCKER_VERSION to 1.13.1. In my case (not plug-able db) it is not useful.

**Comment by Djelibeybi** [comment]
It is true. To successfully build images using the latest Dockerfiles in this repo, you need to run Docker 17.09 or higher. Building the images on a lower version is not supported.

**Comment by burtsevyg** [comment]
Only for info.
When I changed healthcheck

`sed -ie "s|HEALTHCHECK --interval=1m --start-period=5m \\\|HEALTHCHECK --interval=1m --retries=10 \\\|g" 12.2.0.1/Dockerfile`

or remove it, build was a successful.
