### ISSUE TITLE
Provide small Oracle-18c-XE Container Image

### ISSUE THREAD

**Issue by lostiniceland** [oracle/docker-images#1039]
Use-Case:
We are providing our stakeholders with a running application for each feature/bugfix before it is merged to master. For this a ephemeral database-instance is enough.

Problem:
Current Oracle XE releases are still way to heavy for this szenario. Memory consumption and pure disc-size is way beyond any other database (e.g. Postgres image uses 150MB)

Furthermore the container solution for 18c is not yet available. We tried to adopt the 11.2 Docker-files from this repo to 18c with some success, but the image size is still above 10GB!

Request:
Please provide a way to build a stripped Oracle 18c image that only contains the bare minimum to execute SQL (no enterprise-features).

**Comment by nocheinAndi** [comment]
Is there any progress for this?

**Comment by Djelibeybi** [comment]
Yes, we have an 18c Dockerfile for `18.4.0`. Just follow the documentation: https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance

And all the Dockerfiles have been significantly optimized for size since this was opened in 2018, so I'm going to close this now. If you have any related questions, please open a new issue.
