### ISSUE TITLE
Provide a Helm chart for standalone and RAC Oracle deployments on Kubernetes

### ISSUE THREAD

**Issue by luisdavim** [oracle/docker-images#1042]
Please provide a simple way to deploy Oracle databases on Kubernetes

**Comment by Djelibeybi** [comment]
Helm charts are on the roadmap, but there is no ETA for this yet.

**Comment by luisdavim** [comment]
Thanks for the answer, maybe you could keep the ticket open to track the request and see if someone out there is interested in working on it. I might if I get some free time to do it.

**Comment by ctienshi** [comment]
Any update on this issue? I am also currently looking for helm chart to deploy Oracle database.

**Comment by dangrafic** [comment]
Hi any update on this topic? Is there any Helm Chart to deploy Oracle Database standalone or RAC on Kubernetes? By advance thanks

**Comment by ptiggerdine** [comment]
Hi, Is there any update on this. Ideally we would like to pass ASM LUNS to it as well.

**Comment by Djelibeybi** [comment]
Reopened and assigned to @gvenzl (for standalone) and @psaini79 (for RAC).

**Comment by MnrGreg** [comment]
Enabling some form of HA here (even Active/Passive with RAC-One-Node) would open a number of Test/Dev use-cases on Kubernetes. Most Kubernetes platforms are in a constant state of flux, whether it be Draining due to platform maintenance; or nodes coming through Cluster Autoscaling. The availability of a Standalone Oracle DB deployment in the above scenarios is likely too poor for application develop teams.

Is it worth starting a document to discuss approaches for moving an HA solution forward? Could start with some suggestions for simplifying this. For example:
1. Develop raw yaml before templating into Helm
2. Separate the manifests for Standalone, RAC One Node and RAC deployments
3. Descope ASM and start with NFS
4. Develop for a static number of instances (e.g. 3) and descope lifecycle changes such as joining or removing instances

Discuss possible approaches for Kubernetes challenges, for example:
- Clusterware requirement: Public & Private interfaces within a Pod (possibly use Multus CNI)
- Clusterware requirement: Private interface multicast/broadcast capability (again possibly use Multus CNI)
- Which Kubernetes pattern and why: StatefulSet vs Deployment
- ...

**Comment by Djelibeybi** [comment]
Helm charts for standalone Database are here: https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance/charts/oracle-db
