### ISSUE TITLE
Automatic "opatch apply"

### ISSUE THREAD

**Issue by xtender** [oracle/docker-images#1070]
It would be great to have an ability to upload patches into special volume for patches and container installs them automatically (`unzip && cd {patch_number} && opatch apply` for each of them)

**Comment by xtender** [comment]
I did it for own images:
1. created patches directory and put install_patches.sh into this directory:
```
# cat install_patches.sh
#!/bin/bash

unzip  -u ./*.zip
CURDIR=`pwd`

for D in *; do
    if [ -d "${D}" ]; then
        echo =================================================
        echo " *** Processing patch # ${D}... "   # your processing here
        cd "${D}"
        opatch apply -silent
    fi
    cd $CURDIR
done

```
2. added into dockerfile the following commands:

```
COPY --chown=oracle:dba patches $INSTALL_DIR/patches

# Install DB software binaries
USER oracle
RUN chmod ug+x $INSTALL_DIR/patches/*.sh && \
    sync && \
    cd $INSTALL_DIR/patches && \
    ./install_patches.sh

```

**Comment by xtender** [comment]
So I can put downloaded patches into this directory and they will be installed automatically

**Comment by gvenzl** [comment]
What you really want to do is create a patched image that is tagged appropriately, rather than having an image that says `oracle/database:18.3.0-ee` but in fact isn't an 18.3.0-ee image anymore.
You also have to make sure that the database data dictionary has been patched as well, so you can't just startup a image which includes patches against random database files.

You will find a sample of how you can build patched images in [SingleInstane/samples/applypatch](https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance/samples/applypatch)

**Comment by theBNT** [comment]
Thank you @xtender for this suggestion (and your related blog post) and sorry everybody else for reviving this old issue, but i think providing a standardized update mechanism for Oracle Docker images is something of big help for many users, especially since the readily available images arent updated that frequently.

Currently, im trying to patch the [19.3.0](https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance/dockerfiles/19.3.0) with the RU patch 32226239 (provided via file `p32226239_190000_Linux-x86-64.zip`) in order to mitigate a problem which occurs during import into a dockerbased database.

It seems the linked procedure is at least off by the folder structure because opatch quits with
```
ZOP-51: The patch location is not valid for apply, because it doesn't have correct metadata, or it points to a patch directory.
Argument(s) Error... Patch location is not valid for apply
```

After fixing the folder traversal, im running into "File not found or not writable" errors during opatch, so any help appreciated!

**Comment by gvenzl** [comment]
Closing the issue as these image and database versions have been superseded.
Please reopen this ER for 19c if you think this functionality is still useful.
