### ISSUE TITLE
OracleFMWInfrastructure 12.2.1.3 Dockerfile Unknown flag: chown

### ISSUE THREAD

**Issue by xiancao** [oracle/docker-images#1130]
When I tried to build fmw infrastructure docker image 12.2.1.3 using:
<./buildDockerImage.sh -v 12.2.1.3>
I got the following error:
<Step 14/18 : COPY --from=builder --chown=oracle:oracle /u01 /u01
Unknown flag: chown
There was an error building the image.>

I need to change this following line in docker-images/OracleFMWInfrastructure/dockerfiles/12.2.1.3/Dockfile:
<COPY --from=builder --chown=oracle:oracle /u01 /u01 >
to 
<COPY --from=builder /u01 /u01
RUN chown oracle:oracle -R /u01>

My docker version is 17.06.2-ol
OS: oracle devops linux 7.4

**Comment by gvenzl** [comment]
@xiancao, I'm pretty sure that the issue is that your Docker version is too old. `--chown` has been [introduced in Docker 17.09](https://forums.docker.com/t/copy-chown-fails-in-automated-build-unknown-flag-chown/43059/2) and hence it is failing for you with Docker 17.06.
Can you please update your Docker version and see whether the error persists?

@mriccell, feel free to correct me :)

**Comment by xiancao** [comment]
@gvenzl yes, you are right. I verified we can use --chown flag in docker 18.03.1. 
@mriccell our test env is still using 17.06 now. Maybe other people will hit this error as well. It's your call whether revert it or not.

**Comment by mriccell** [comment]
This has been corrected in PR #1176
