### ISSUE TITLE
Permission becomes 54652 (inside container)and 1000 (in my server) after volume mount 

### ISSUE THREAD

**Issue by aivl2018** [oracle/docker-images#1199]
Hi Team,

After running container i am getting permission issue.
As i have installed docker using root user.
For my app user, given permission & running it via appuser
uid=54652(appuser)gid=54652(appuser) groups=54652(appuser),989(docker)

Inside container =
drwxrwxrwx  3  **54652  54652** 4096 Mar 12 07:57 user_projects

In my server =
drwxr-x--- 3 1000 1000 4096 Mar 12 03:57 domains

How to solve this issue ?

**Comment by aivl2018** [comment]
Hello gvenzl,

Can we access both volume mount directories (inside container and in my server)?
I can see if i change permission of external volume from root then i am not able to access inside container directory as which then owned by root.

**Comment by gvenzl** [comment]
Hi @aivl2018, this is just the way how Docker works. Whatever user runs inside the container (which shouldn't be `root` due to security reasons but way too many people just run under `root` for simplicity) and writes files, these files will get the user's UID. If that user UID happens to be different than the one you have in the outside world, then you have a mismatch, nothing different here, just the way Linux itself works.

There are a couple of ways how you can get around it though.

1) Use named volumes, see https://docs.docker.com/storage/volumes/
2) Change the ownership of your folder to the UID of the container user
3) Change the permissions of your folder so that the UID used inside the container has write permissions

**Comment by aivl2018** [comment]
Thanks gvenzl.
So as of now i am giving 777 permission to my external volume & it works fine for both inside container & local volume.
Giving all permission is preferable or not ?

**Comment by gvenzl** [comment]
Great!

Depending on what you are after. If you just run this on your machine for a dev environment than this is fine. Otherwise it would be wiser to change the ownership to 54321 via `chown -R 54321 <volume directory>`

**Comment by aivl2018** [comment]
Okay. One last thing.
Now i have weblogic installed in container. Now i need to use external apache server which is to be integrate with weblogic docker container. 
_Due to some reason i am unable to use samples/12213-webtier-apache._
How to do it ?

**Comment by Djelibeybi** [comment]
Please ask that question in a new issue.

**Comment by aivl2018** [comment]
@Djelibeybi 
Okay . Submitted a new issue : https://github.com/oracle/docker-images/issues/1203
