### ISSUE TITLE
Building an OGG 4 Microservices image in an air-gapped system

### ISSUE THREAD

**Issue by alesana-san** [oracle/docker-images#1285]
Hi!

I have a `zip` file for building my OGG 4 Microservices image. But on my work we don't have an Internet access so I can't install `oracle-softwarecollection-release-el7` (in my case) and `rh-nginx18` (but we have a local repo with `openssl`, `java-1.8.0-openjdk-headless` and `python-requests`.
I thought to add some lines to `oracle-linux` image (adding repos, etc) and leave `OGG` Dockerfile untouched and build it normally.
And it is possible to download some `rpm`s from the Internet and pass them to the inner network. I could build an image and then send it inside but it would be very large to send it (inner restrictions).
So is it possible to somehow preset repos and packages to make OGG image build successfully?

**Comment by Djelibeybi** [comment]
Why can't you build the image on a non-airgapped system and then transfer the built image into the airgapped environment? If this is not possible, you will still need to run the build on a system connected to the internet to determine which packages are required by the build system so that you can mirror those internally.

**Comment by alesana-san** [comment]
@Djelibeybi it's actually the same as #1260. I have a zip but transfer of a pre-built image is not suitable for me. In case if there are very few packages I need to make it work and they are small enough so I could transfer them inside our network and then install them.

**Comment by Djelibeybi** [comment]
You're commenting on the Internet now, so clearly you have some access at some point. :) You'll need to run this build on an Internet-connected system to determine which packages are required and then download and copy those packages across into your airgapped system. You can download packages from yum.oracle.com or use a mirror server (which is the preferred option).

I'm going to close this issue now because determining how to build our images in an airgapped system is beyond the scope of the support in this repository. If you have Oracle support, you may open an SR at https://support.oracle.com for further assistance.
