### ISSUE TITLE
Should prebuild db or not?

### ISSUE THREAD

**Issue by tstibbs** [oracle/docker-images#1304]
I have built a 12c SE2 container (see https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance/dockerfiles/12.2.0.1). When this first starts, it spends 5-10 minutes doing the following things:
- Copying database files
- Creating and starting Oracle instance
- Completing Database Creation
- Creating Pluggable Databases

Clearly, I'd like the container to start quicker if possible. Is there any reason not to commit the container after this setup has been completed? Equally, is there any reason that this startup/setup is not performed as part of the docker build?

I can see instructions for creating a prebuilt db (https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance/samples/prebuiltdb), but given that this is not the default, I assume there are some disadvantages to this approach. Can someone give me an idea of what these disadvantages are?

**Comment by gvenzl** [comment]
Hi @tstibbs,

There are several downsides when you prebuild the database and put it into the image:

1. The image will become bigger, sometimes much bigger. Granted, I personally never saw an issue with that, it's not like that one constantly pulls the image over and over again as it's not changing much, and even if, the bandwidth of these days should be sufficient for that. Yet, the image size constantly seems to cause the biggest cry out. "Oh, the Oracle database image is so big, can it not be as small as Postgres?". --> "Errr, no! The Oracle Database has about 1000 useful features more than Postgres, that compiled code needs to sit somewhere. Oh yeah right, that's what we have binaries and libraries for..."
2. Host-only volumes won't extract the database files into your volume, actually your volume will mount over them and all of a sudden your database files disappear. For example, look at the ORACLE_BASE inside the container:

```
[oracle@localhost ~]$ docker run --name test -ti oracle/database:19.3.0-ee bash
[oracle@84ca1c8ebd1b ~]$ ls -al /opt/oracle
total 40
drwxr-xr-x. 1 oracle dba   282 Aug  9 03:06 .
drwxr-xr-x. 1 root   root   28 Aug  9 03:07 ..
-rwxr-xr-x. 1 oracle dba  1050 Apr 26 18:08 checkDBStatus.sh
drwxr-xr-x. 1 oracle dba     0 Aug  9 03:03 checkpoints
-rwxr-xr-x. 1 oracle dba  3088 Apr 26 18:08 createDB.sh
-rw-r--r--. 1 oracle dba  9204 Apr 26 18:08 dbca.rsp.tmpl
drwxrwxr-x. 1 oracle dba   212 Aug  9 03:03 diag
drwxrwx---. 1 oracle dba    80 Aug  9 03:03 oraInventory
drwxr-xr-x. 1 oracle dba     0 Aug  9 02:57 oradata
drwxr-xr-x. 1 oracle dba     6 Aug  9 02:57 product
-rwxr-xr-x. 1 oracle dba  6526 Apr 26 18:08 runOracle.sh
-rwxr-xr-x. 1 oracle dba  1015 Apr 26 18:08 runUserScripts.sh
drwxr-xr-x. 1 oracle dba    24 Aug  9 02:57 scripts
-rwxr-xr-x. 1 oracle dba   758 Apr 26 18:08 setPassword.sh
-rwxr-xr-x. 1 oracle dba   678 Apr 26 18:08 startDB.sh
```
In there we find all the good stuff that we expect from an ORACLE_BASE including some extra shell scripts that make our Docker image the Docker image. Now let's do following, let's create a new folder `empty` and put one file into it called `bla` and then mount that folder into `/opt/oracle`:

```
[oracle@84ca1c8ebd1b ~]$ exit
exit
d[oracle@localhost ~]$ docker rm -v test
test
[oracle@localhost ~]$ docker run --name test -v /home/oracle/empty:/opt/oracle/ -ti oracle/database:19.3.0-ee bash^C
[oracle@localhost ~]$ mkdir empty
[oracle@localhost ~]$ touch empty/bla
[oracle@localhost ~]$ ls -al empty/
total 4
drwxrwxr-x.  2 oracle oracle   16 Aug  8 23:18 .
drwx------. 17 oracle oracle 4096 Aug  8 23:18 ..
-rw-rw-r--.  1 oracle oracle    0 Aug  8 23:18 bla
[oracle@localhost ~]$ docker run --name test -v /home/oracle/empty:/opt/oracle/ -ti oracle/database:19.3.0-ee bash
[oracle@75419c712bfb ~]$ ls -al /opt/oracle
total 0
drwxrwxr-x. 3   1000 1001 30 Aug  9 03:18 .
drwxr-xr-x. 1 root   root 28 Aug  9 03:07 ..
-rw-rw-r--. 1   1000 1001  0 Aug  9 03:18 bla
drwxr-xr-x. 1 oracle dba   0 Aug  9 02:57 oradata
```
There you go, our entire home is pretty much gone (except the `oradata` folder which seems to be preserved because it's the volume). Let's have a look at `oradata`:

```
[oracle@75419c712bfb ~]$ ls -al /opt/oracle/oradata/
total 0
drwxr-xr-x. 1 oracle dba   0 Aug  9 02:57 .
drwxrwxr-x. 3   1000 1001 30 Aug  9 03:18 ..
```

It's empty, which is OK because no database has been created yet. Ok, so what happens if we map `empty` over `/opt/oracle/oradata` instead?

```
[oracle@75419c712bfb ~]$ exit
exit
[oracle@localhost ~]$ docker rm -v test
test
[oracle@localhost ~]$ docker run --name test -v /home/oracle/empty:/opt/oracle/oradata -ti oracle/database:19.3.0-ee bash
[oracle@6b7d3583434d ~]$ ls -al /opt/oracle/oradata
total 0
drwxrwxr-x. 3   1000 1001  30 Aug  9 03:18 .
drwxr-xr-x. 1 oracle dba  282 Aug  9 03:06 ..
-rw-rw-r--. 1   1000 1001   0 Aug  9 03:18 bla
drwxr-xr-x. 2 root   root   6 Aug  9 03:18 oradata
[oracle@6b7d3583434d ~]$ ls -al /opt/oracle/oradata/oradata/
total 0
drwxr-xr-x. 2 root root  6 Aug  9 03:18 .
drwxrwxr-x. 3 1000 1001 30 Aug  9 03:18 ..
```
What's that? Now we have the file `bla` in `/opt/oracle/oradata` (as expected) but we have another `oradata`, now that path just got screwed but it doesn't matter because our data files would have disappeared anyway.

What does work, are named volumes (only, unfortunately). So let's create a named volume:
```
[oracle@localhost ~]$ docker rm -v test
test
[oracle@localhost ~]$ docker volume create test
test
[oracle@localhost ~]$ docker volume inspect test
[
    {
        "CreatedAt": "2019-08-08T23:24:21-04:00",
        "Driver": "local",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/volumes/test/_data",
        "Name": "test",
        "Options": {},
        "Scope": "local"
    }
]
```
Great, the volume is created, but it's located at `/var/lib/docker/volumes/test/_data`. What's the issue with that, well it's owned by `root` and we don't have access to it unless we have root:
```
[oracle@localhost ~]$ ls -al /var/lib/docker/volumes/test/_data
ls: cannot access /var/lib/docker/volumes/test/_data: Permission denied
[oracle@localhost ~]$ ls -al /var/lib/docker/volumes
ls: cannot open directory /var/lib/docker/volumes: Permission denied
[oracle@localhost ~]$ ls -al /var/lib/docker
ls: cannot open directory /var/lib/docker: Permission denied
```
But let's ignore that for now and create a container having the named volume mapped to `/opt/oracle`. Creating the container will take longer now, because the named volumes copies everything out first so that it's not lost. Let's see:
```
[oracle@localhost ~]$ docker run --name test -v test:/opt/oracle -ti oracle/database:19.3.0-ee bash
[oracle@92cb66262dee ~]$ ls -al /opt/oracle
total 20
drwxr-xr-x. 1 oracle dba   282 Aug  9 03:26 .
drwxr-xr-x. 1 root   root   28 Aug  9 03:07 ..
-rwxr-xr-x. 1 oracle dba  1050 Apr 26 18:08 checkDBStatus.sh
drwxr-xr-x. 1 oracle dba     0 Aug  9 03:03 checkpoints
-rwxr-xr-x. 1 oracle dba  3088 Apr 26 18:08 createDB.sh
-rw-r--r--. 1 oracle dba  9204 Apr 26 18:08 dbca.rsp.tmpl
drwxrwxr-x. 1 oracle dba   212 Aug  9 03:26 diag
drwxrwx---. 1 oracle dba    80 Aug  9 03:26 oraInventory
drwxr-xr-x. 1 oracle dba     0 Aug  9 02:57 oradata
drwxr-xr-x. 1 oracle dba     6 Aug  9 03:26 product
-rwxr-xr-x. 1 oracle dba  6526 Apr 26 18:08 runOracle.sh
-rwxr-xr-x. 1 oracle dba  1015 Apr 26 18:08 runUserScripts.sh
drwxr-xr-x. 1 oracle dba    24 Aug  9 03:26 scripts
-rwxr-xr-x. 1 oracle dba   758 Apr 26 18:08 setPassword.sh
-rwxr-xr-x. 1 oracle dba   678 Apr 26 18:08 startDB.sh
```
And indeed, all our files are still there and we have them now in our named volume. Great, so we can use this for database files, right? Sure, only downside to it? Well, if you ever want to get access to the database files, say because you take advantage of pluggable databases, or you want to see a log or trace file, well now you will have to convince your UNIX admin to either give you the `root` password or `sudo` rights, also not that great:
```
[oracle@92cb66262dee ~]$ exit
exit
[oracle@localhost ~]$ sudo ls -al /var/lib/docker/volumes/test/_data
[sudo] password for oracle:
total 20
drwxr-xr-x. 1 54321 54322  282 Aug  8 23:26 .
drwxr-xr-x. 1 root  root    10 Aug  8 23:24 ..
-rwxr-xr-x. 1 54321 54322 1050 Apr 26 14:08 checkDBStatus.sh
drwxr-xr-x. 1 54321 54322    0 Aug  8 23:03 checkpoints
-rwxr-xr-x. 1 54321 54322 3088 Apr 26 14:08 createDB.sh
-rw-r--r--. 1 54321 54322 9204 Apr 26 14:08 dbca.rsp.tmpl
drwxrwxr-x. 1 54321 54322  212 Aug  8 23:26 diag
drwxr-xr-x. 1 54321 54322    0 Aug  8 22:57 oradata
drwxrwx---. 1 54321 54322   80 Aug  8 23:26 oraInventory
drwxr-xr-x. 1 54321 54322    6 Aug  8 23:26 product
-rwxr-xr-x. 1 54321 54322 6526 Apr 26 14:08 runOracle.sh
-rwxr-xr-x. 1 54321 54322 1015 Apr 26 14:08 runUserScripts.sh
drwxr-xr-x. 1 54321 54322   24 Aug  8 23:26 scripts
-rwxr-xr-x. 1 54321 54322  758 Apr 26 14:08 setPassword.sh
-rwxr-xr-x. 1 54321 54322  678 Apr 26 14:08 startDB.sh
```
3. How are you going to apply patches and keep your data? Patching binaries is easy, you just build a new image with the patched binaries. But if you have the database inside the container image, well how do you get that database that is already running into that image that you are about to patch? It gets messy.
4. You cannot decide what the database name should be, which is a one time choice during database creation
5. You cannot decide what the database characterset should be, which is a one time choice during database creation.

I think that's all, perhaps something more comes to mind but essentially all of the above are the reason why we (have/want to) create the database during startup time. That being said, there is an idea in a PR to pass on prebuilt database or not as a build argument. I like that idea, one can decide for their use case, but that requires first to get rid of the `VOLUME` instruction (another topic, it cannot be undone in an inherited container, nor can it be conditional) and that requires some more testing. Hence the easiest today is the manual steps provided.

I hope this helps!

**Comment by gvenzl** [comment]
As my dear friend @martindsouza pointed out to me, it could be beneficial for folks to also hear the good reasons why you do want to prebuild the databases into the image. In a nutshell, whenever you want a quick startup time of something static/transient. What do I mean by that, let's take a closer look:

You may want to prebuilt a DB inside an image, when:

1. You don't care about any of the above, obviously :)
2. You want a test database for unit/regression tests. You want to be able to just boot up a database, run the tests, throw it away again, no need to persist anything after that. In this case, you probably also want to consider to already have a starter schema, and perhaps even test data, in the database as well so that your unit tests don't have to go through a setup phase. Ideally, in your build environment you not only spit out the application artifacts but also a database Docker image with the data model reflecting the current development state of your code. Of course there are various ways how you can generate a Docker image automatically, either completely custom or use some of the scripts here and amend them for your needs, etc. The idea being, startup database ready to go, execute tests, throw it away.
3. Any CI/CD pipeline or workflow where waiting ~5 minutes for a DB to startup is too long and/or would time out.
4. To give your developers/users a consistent database environment to work with across the board. No more "turns out my configuration parameter is different than yours" or "I don't remember anymore how I have set it up", etc.
