### ISSUE TITLE
Error creating XE 11.2.0.2 Image

### ISSUE THREAD

**Issue by holodny** [oracle/docker-images#140]
_While building the initial XE 11.2.0.2 I get this error (I think it's an error, it's in red -- bolded below):_

Archive:  oracle-xe-11.2.0-1.0.x86_64.rpm.zip
   creating: Disk1/
   creating: Disk1/upgrade/
  inflating: Disk1/upgrade/gen_inst.sql  
   creating: Disk1/response/
  inflating: Disk1/response/xe.rsp   
  inflating: Disk1/oracle-xe-11.2.0-1.0.x86_64.rpm  
**sysctl: setting key "kernel.sem": Read-only file system
/var/tmp/rpm-tmp.dysS0W: line 257: [: 18446744073692774399: integer expression expected
/var/tmp/rpm-tmp.dysS0W: line 271: [: 18446744073692774399: integer expression expected
sysctl: setting key "fs.file-max": Read-only file system**
Executing post-install steps...
You must run '/etc/init.d/oracle-xe configure' as the root user to configure the database.

_Later, the install hangs on "Configuring database"._

Do you want Oracle Database 11g Express Edition to be started on boot (y/n) [y]:
Starting Oracle Net Listener...Done
**Configuring database...**

_When I do "sudo docker ps -a"  I see a running container that has a command of_ **"/bin/sh -c 'unzip $I"**

**Comment by gvenzl** [comment]
The errors above result out of the rpm installation itself. Inside a Docker container it is not permitted to set those kernel parameters. Those parameters have to be set on the host and once done, can be ignored. Please refer to the [Oracle Database Express Edition Installation Guide](https://docs.oracle.com/cd/E17781_01/install.112/e18802/toc.htm#BABJFAIA) for the minimum requirement.

If the configuration faces an issue it would indicate that on the stdout:

Do you want Oracle Database 11g Express Edition to be started on boot (y/n) [y]:
Starting Oracle Net Listener...Done
Configuring database...
**Database Configuration failed.  Look into /u01/app/oracle/product/11.2.0/xe/config/log for details**
Removing intermediate container 0cfec73009f4

Are you sure that the installation is hanging and not just progressing slowly? Have you made sure that the base image has enough space available?

**Comment by brunoborges** [comment]
I'll close this issue for now. If there is anything we can do in the Dockerfiles to prevent this problem, we'll reopen this.

**Comment by rickyrocker** [comment]
I can't speak for all the problems listed but I can say that these 2 items:

/var/tmp/rpm-tmp.dysS0W: line 257: [: 18446744073692774399: integer expression expected
/var/tmp/rpm-tmp.dysS0W: line 271: [: 18446744073692774399: integer expression expected

it is very likely that:
1. the values shown are not random but the value of shm kernel parameters on the user's system
2. and the user is installing using the bash shell rather than the korn shell

The errors are occurring because in checking whether the user's shm values are large enough oracle does a logical if [ shmparmvalue -lt requiredshmparmvalue ]; then fail in the installation script and in bash shell, the value above fails because it is simply too big to be recognised as an integer (the same script will work in the Korn shell)

So in fact - these "errors" simply confirm that the user's kernel parameters are big enough ...so big that they can't actually be recognised as integers in the bash shell.

On the assumption that the user is able to access XE is normal they can thus be ignored. In order to get rid of them the user could alternatively switch the installation to use the Korn shell.

I hope this helps.

**Comment by xiaoyan1985** [comment]
Have you solved this problem ?

**Comment by holodny** [comment]
This problem is no longer an issue for me after trying an installation today using the latest directions at https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance for oracle/database:11.2.0.2-xe.  Thank you!
