### ISSUE TITLE
Gender-neutral readme are not grammatically correct

### ISSUE THREAD

**Issue by dmytro-sylaiev** [oracle/docker-images#1407]
https://github.com/oracle/docker-images/commit/76aaed21be5ac7a38a6cd2a5970071920fad9c16#diff-60c937af3f24e7b30d25c60885c985cfR19

>  In case the user does not want to be prompted, they can use the -confirm option.

Should be replaced with 
> ... **users don't** want to be prompted, they can use the -confirm option.

**Comment by KyleAure** [comment]
The subject of the sentences in this paragraph is "the user."  Since the gender of "the user" is unknown or non-binary the singular-nonbinary use of `they` is being used.  A similar use would be if I were introducing a friend who preferred to use the pronoun they, I would say, “This is my friend, Jay. I met them at work.” 

Reference: https://www.merriam-webster.com/words-at-play/singular-nonbinary-they

**Comment by Djelibeybi** [comment]
@KyleAure is correct regarding the use of the singular non-binary forms of "they" and "them".
