### ISSUE TITLE
DB does not start any more if oradata folder is emptied with stopped container 

### ISSUE THREAD

**Issue by gggeek** [oracle/docker-images#1533]
I am trying to integrate Oracle Xe in a docker-compose project.

For persisting data, I use a host mount instead of volume for the oradata folder, and it works fine on first start of the container.
However, if I: stop the container, remove all files in the oradata folder, and start it again, the db does not start any more.

The main problem seems to be with how the db is not natively capable of (re)creating the datafiles if those are missing at boot, and what runOracle.sh currently does.

This could be fixable f.e. by keeping copies of empty data files in a separate location and having a shell script running at container start that copies them over if oradata dir is empty. Not that different from what runOracle.sh currently does (except for the fact that runOracle.sh moves the existing files, which makes it work only once and break if the volume gets manually cleaned up before a container restart).
Maybe there is even a better, native solution that I am not aware of that would create data files... my oracle-fu is getting rusty

**Comment by gggeek** [comment]
Somewhat related? https://github.com/oracle/docker-images/issues/640#issuecomment-441304170

**Comment by Djelibeybi** [comment]
The database is created on start of the container, so why are you deleting the files?

**Comment by gggeek** [comment]
I am deleting the db files Because my host is low on hard disk space, and the goal for the container which I am building is to be a kind of test/scratch/ci database.
I'd like to f.e. be able to reset the db data daily if needed, but also to be able to keep the data for a longer period, with the container turned off.

The  pattern I have been using with success with other databases (mysql, postgres, sqlserver) so far is:
- build the image: once
- (start it, load the db with data, run my tests, stop it, remove data files and log files): N times

I guess that I could also 'free up disk space' by logging in as dba and dropping all existing schemas except 'system' ones, but that seems slightly unsafer (changes to the system schemas would still persist) and forces me to develop database-specific cleanup scripts...

**Comment by Djelibeybi** [comment]
As you've discovered, Oracle isn't like other databases. It cannot survive the removal of its data files. 

Keep in mind that Oracle stores everything per user, so the clean-up script is not database-specific, it's user specific. Just drop the user (with CASCADE) and all its data goes too.

**Comment by gggeek** [comment]
I did some testing, and found out that in the end the solution was simpler than expected.
If the oradata folder is manually wiped, all that is required for the db-creation procedure to kick in again on the next start of the container is to make sure that /etc/oratab is cleaned up and 4 symlinks removed...

**Comment by mark-au** [comment]
I think you resolved this issue with #1537, thanks!

**Comment by raduv7** [comment]
> I did some testing, and found out that in the end the solution was simpler than expected. If the oradata folder is manually wiped, all that is required for the db-creation procedure to kick in again on the next start of the container is to make sure that /etc/oratab is cleaned up and 4 symlinks removed...

Can you provide some detail on which symlinks I should remove? I'm using oracle enterprise 19.3 and facing the same issue, but in etc folder there are many more symlinks. This is the complete list: system-release -> oracle-release, rc.local -> rc.d/rc.local, rc0.d -> rc.d/rc0.d ... rc6.d -> rc.d/rc6.d, mtab -> ../proc/self/mounts, localtime -> ../usr/share/zoneinfo/UTC, init.d -> rc.d/init.d

**Comment by oraclesean** [comment]
@raduv7 the links you'll need to remove/recreate are those that point to `/opt/oracle/oradata/dbconfig` and include `/etc/oratab`. You can find a full list of links created in the container in the [`runOracle.sh` script](https://github.com/oracle/docker-images/blob/main/OracleDatabase/SingleInstance/dockerfiles/19.3.0/runOracle.sh).

However, removing these symlinks is unnecessary since this script should clean them up automatically. When the container starts, it looks for a hidden file called `.${ORACLE_SID}.created` in the data directory. If the mapped volume directory was removed entirely, that file is gone, too. But, if only database files were deleted, the startup script will see that file and assume a database exists.

If that's the case, navigate to the mapped volume, confirm the hidden file exists (via `ls -la`), then remove it. Then, restart the container.

For those looking for information on persisting data on volumes or for those wanting to clone data, look through this [free chapter on persistence](https://oraclesean.com/blog/oracle-on-docker-is-now-available) for Oracle databases running in containers.

**Comment by raduv7** [comment]
thanks @oraclesean
