### ISSUE TITLE
About base image oracle/jdk

### ISSUE THREAD

**Issue by feici02** [oracle/docker-images#154]
Hi,
I can't find image _oracle/jdk_ on Docker Hub, there is only _oralce/openjdk_.
But it is used by products like Weblogic and Tuxedo as the base image.
Why?

Thanks,
feici02

**Comment by imnuh** [comment]
Check the oraclejdk folder. You can build it from there.

**Comment by feici02** [comment]
@imnuh Thanks, I found this:
`docker pull huhgawz/oraclelinux-oraclejdk`

**Comment by brunoborges** [comment]
The reason you don't see `oracle/jdk` on DockerHub is because we don't publish commercial software to DockerHub. Nor should other folks without proper license agreement do that either... you know, like huhgawz :-)

Go to [OracleJDK](https://github.com/oracle/docker-images/tree/master/OracleJDK) and build the oracle/jdk image. Publish on your internal registry server, and then you can use it for whatever you want.

**Comment by feici02** [comment]
@brunoborges Thank you for the detailed explanation.
That's the answer I want to get.
