### ISSUE TITLE
how to use this with RMAN to restore a database

### ISSUE THREAD

**Issue by seninp** [oracle/docker-images#1586]
Hello:

Thank you for making this available. 

I have a database backup I would like to recover, but can't get past the controlfile recovery attempt. Currently, the database is mounted by default on boot, shutdown+nomount startup `rman` command combo (for initiating the backup restore) shuts the instance down. I am stuck... tried with both: express edition and standard.

Thank you!

**Comment by gvenzl** [comment]
Hi @seninp,

You are probably better off asking this question on the [Oracle Database Forums](https://community.oracle.com/community/groundbreakers/database) rather than here.

We can help with questions about the scripts provided in this repository but we don't necessarily know the answers to questions on all the functionality of the products that are containerized by these scripts.
