### ISSUE TITLE
Database: trapping SIGKILL seems to be discouraged

### ISSUE THREAD

**Issue by srmo** [oracle/docker-images#1603]
You are using `trap SIGKILL` in the runOracle.sh scripts.
This is discouraged according to https://github.com/koalaman/shellcheck/wiki/SC2173 which also is noted in the signal man page (http://man7.org/linux/man-pages/man7/signal.7.html)
> The signals SIGKILL and SIGSTOP cannot be caught, blocked, or ignored.

What am I missing here? What's your rationale behind this? Did you take any measures in the oracle-linux base image?

**Comment by Djelibeybi** [comment]
Without an init system in the container, `runOracle.sh` becomes PID1. You have to trap signals inside PID1 to clean up any child processes: https://medium.com/@gchudnov/trapping-signals-in-docker-containers-7a57fdda7d86

I suspect `SIGKILL` is a legacy signal still being trapped with only `SIGTERM` actually being needed these days. I seem to recall that Docker used to try a `SIGTERM` followed by `SIGKILL` ages ago. We probably haven't updated since then.

Note that we don't take any measures in the base image, because nothing else is running to trap the signal in the higher image.

**Comment by Djelibeybi** [comment]
Assigning to @gvenzl to review. It may be that we just remove the trap in these fancy modern times. :) Also pinging @mriccell because I know the WebLogic images trap as well.

**Comment by gvenzl** [comment]
Yeah, this seems to be a legacy thing at first glance. Will have a closer look and see whether we had any particular reason that we introduced it. Thanks for the heads-up!

**Comment by Djelibeybi** [comment]
Here's the original issue: https://github.com/oracle/docker-images/issues/146 -- seems Moby has stopped issuing `SIGKILL` in the interim. Not that we could trap it anyway.
