### ISSUE TITLE
Too heavy, too slow...

### ISSUE THREAD

**Issue by KamilJedrzejuk** [oracle/docker-images#1678]
Can You explain me why Oracle docker image starts very slow?

I had to create my own image, beacuse i wanted ommit a database creation step.
You can check my repo:
https://github.com/KamilJedrzejuk/oracle18c-xe

I can't use original image with Testcontainers lib in my integration test.
if on the other hand we look at the PostgreSQL is very fasts and light in tests. 

Please check nice example
https://kiview.github.io/testcontainers-grails-workshop/ postgresql is less than 300mb...

For me 
This is ridiculous:

IMPORTANT: The resulting images will be an image with the Oracle binaries installed. On first startup of the container a new database will be created, the following lines highlight when the database is ready to be used:

#########################
DATABASE IS READY TO USE!
#########################

**Comment by KamilJedrzejuk** [comment]
Is anyone who can help?
@gvenzl 
?

**Comment by KamilJedrzejuk** [comment]
So I guess problem is solved?

**Comment by Djelibeybi** [comment]
Sorry, I was closing out stale issues and must have closed this one by mistake.

**Comment by Djelibeybi** [comment]
Have you tried using the Prebuild DB example: https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance/samples/prebuiltdb 

As for size, that's not something we can do much about. Oracle Database is pretty big. You can try applying the submitted code to create `-slim` variants from https://github.com/oracle/docker-images/pull/1666 and see if that helps.

**Comment by Djelibeybi** [comment]
Note that all of your Docker Hub images are violations of the license to which you agreed when you downloaded the Oracle XE binaries. You are not permitted to redistribute those binaries in any way. I strongly encourage you to remove them from public view before someone from Oracle's legal team detects them and issues a DMCA request for their removal.

**Comment by KamilJedrzejuk** [comment]
Ok I,ve removed.

**Comment by Djelibeybi** [comment]
Thanks. Let us know if the Prebuilt DB and/or the `-slim` variants work for your use case too.

**Comment by lukaseder** [comment]
I'm coming here from a Twitter discussion: https://twitter.com/gmarziou/status/1361700331483234307

I understand that these things are difficult to move forward at Oracle. I've been in touch with numerous people at Oracle about this topic, including e.g. @gvenzl. I just want to stress that pretty much all of Oracle's competition, including IBM with both Db2 *and* the arcane Informix, or Microsoft with SQL Server (they even had to adapt everything to work on Linux, first!!), and obviously PostgreSQL, just to name a few (a few more: CockroachDB, Exasol, Firebird, HANA, Ignite, MariaDB, MemSQL (now SingleStore), MySQL) make working with Docker:

- *A lot* easier
- *A lot* faster
- *A lot less* lawyer-y

To be fair, an example that is harder to work with: Sybase ASE. Yes, given [Larry's only ever tweet](https://twitter.com/larryellison/status/210503900887924736), Oracle is still doing better than SAP. Oh wait. No. HANA is also by SAP. 😁

@gvenzl recently asked me to join a product meeting at Oracle where Oracle would reach out to the community to learn what Oracle can improve with respect to developer friendliness, especially in a context of losing to the competition.

This is one of the top issues that comes to my mind from a developer perspective. Yes, things were a lot worse in the past in pre-docker days, and we're also discussing this publicly on github instead of via a closed MOS SR. But things could be *much* better by now with regards to this docker integration. This issue here could be one of Oracle's top dev friendliness priorities. Alas, it was auto-closed twice.

Look at how I install SQL Server 2019:

```
docker pull mcr.microsoft.com/mssql/server:2019-latest
docker run -e ACCEPT_EULA=Y -e SA_PASSWORD=Test1234 -e MSSQL_PID=Express -p 1433:1433 --name SQLSERVER2019 -d mcr.microsoft.com/mssql/server:2019-latest
```

And it runs fast. Isn't that also what everyone working at Oracle internally on various products, like e.g. SQL Developer, APEX, SQL*Plus, Enterprise Manager, ojdbc, etc etc. would want for themselves as well?

**Comment by gmarziou** [comment]
My own experience.

My pre-built (empty) Oracle 19 Standard image is 8 GB large, and 13 GB large once schema is instantiated.

To share it with my team, I needed to use an internal private docker registry, after several failed attempts to upload it by `docker push` over a bad network because of forced remote working in COVID-19 times, I ended up splitting it up in smaller parts using `tar`, uploading them using `sftp` and then pushing it locally. Fortunately, pulling worked better. Although, I had to request increasing disk space on our registry to support multiple versions. I can't imagine fully automating this process in Jenkins.

Startup time is 40 seconds while Postgresql starts up in few seconds. This impacts the way we write unit tests.

We use docker only for development and testing.
If project would have been a green field one, this bad developer experience would have lead us to choose Postgresql but this is a 10 years-old project so....

**Comment by Djelibeybi** [comment]
Please continue this discussion here: https://github.com/oracle/docker-images/issues/1862

**Comment by lukaseder** [comment]
Thanks, @Djelibeybi. @gmarziou: Best copy your comment to the new issue as well :)

**Comment by gvenzl** [comment]
> Note that all of your Docker Hub images are violations of the license to which you agreed when you downloaded the Oracle XE binaries. You are not permitted to redistribute those binaries in any way. I strongly encourage you to remove them from public view before someone from Oracle's legal team detects them and issues a DMCA request for their removal.

Just to clarify, Oracle Database 18c XE is under the [Oracle Free Use Terms and Conditions](https://www.oracle.com/downloads/licenses/oracle-free-license.html) and allows for redistribution!
