### ISSUE TITLE
ORA-12541: TNS:no listener

### ISSUE THREAD

**Issue by phani87** [oracle/docker-images#1715]
Hi,

I am currently facing ORA-12541: TNS:no listener issue when I try to connect from my Python App. I can connect to DB from within the container and even the listener is running. I am not sure why this error is occurring. Can you please help ?

**Comment by Djelibeybi** [comment]
I'm assigning both @gvenzl (from the Database team) and @cjbj who may be able to assist from the Python side. You will need to give a lot more information though about your container configuration and how (and from where) you're trying to connect. The information provided is not sufficient for us to determine a root cause.

**Comment by cjbj** [comment]
@onmp is the Net expert.

**Comment by phani87** [comment]
NVM, I figured my mistake out. Thanks anyways for your quick response.
