### ISSUE TITLE
OracleDatabase - SingleInstance - 18.4.0-XE

### ISSUE THREAD

**Issue by ssbano** [oracle/docker-images#1719]
Is there any special reason for the docker version to be 17.09? - I am using Docker 1.13.X

MIN_DOCKER_VERSION="17.09"
https://github.com/oracle/docker-images/blob/master/OracleDatabase/SingleInstance/dockerfiles/buildDockerImage.sh

Best Regards,
Fábio Sbano

**Comment by Djelibeybi** [comment]
For the XE image it's probably ok to use that very, very old version of Docker, but it wouldn't work for any of the non-XE images because it either doesn't support multi-stage builds or doesn't support the `chown` parameter in the `COPY` directive. Either way, Docker 1.13.x is woefully old. 

I'll assign this to @gvenzl because it'll be either his or the DB engineering team's decision whether to  modify this requirement or not. There may be other functionality required by the Database itself that 1.13 doesn't provide.

**Comment by ssbano** [comment]
Thank you very much,

Fabio Sbano
