### ISSUE TITLE
Executing user defined setup scripts with wrong user in Oracle Database 18c (18.4.0) Express Edition (XE)

### ISSUE THREAD

**Issue by rprodan** [oracle/docker-images#1881]
I successfully built a Docker image containing Oracle Database 18c (18.4.0) Express Edition (XE). In addition I have my custom setup script with `sql` extension, say `01_users.sql` with the following statement

```sql
CREATE USER INVENTORY_ITEMS IDENTIFIED BY galaxy;
```

I mounted the local directory containing my custom script according to the documentation from [Running scripts after setup and on startup](https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance#running-scripts-after-setup-and-on-startup). The script is successfully processed after the database initialization but I got the following error.

> ORA-65096: invalid common user or role name

This error is expected since custom scripts with `sql` extension are being executed with wrong user. In file  `runOracle.sh` I observed this sqlplus connection to the database.

> $ORACLE_HOME/bin/sqlplus / as sysdba

If my understanding is correct this connection is used to log into the **CDB root container** (CDB$ROOT) database. Instead my scripts should be executed against **plugabble database**. Indeed when I modify the connection command in `runOracle.sh` everything works as expected.

----

Modifying the file `runOracle.sh` seems the wrong approach for me since this file is mainteined by Oracle team but in the current circumstances I don't see any other options.

- Is there any installation/configuration step I missed when running setup scripts?
- Should I alter the session in the beginning of my custom script?

I appreciate your help and support.

**Comment by rprodan** [comment]
I added the session control statement at the beginning of each of my custom scripts. 

```sql
ALTER SESSION SET CONTAINER = XEPDB1;
```

It was necessary to add this statement in each custom script because the logic in `runOracle.sh` is performing a new connection for each custom script. With this workaround all operations will be performed inside the only PDB (pluggable database) that XE supports.

I would still like to hear your opinion about this approach.

**Comment by gvenzl** [comment]
Hi @rprodan,

You are correct, the SQL scripts are automatically connected to the container database (CDB). Oracle's Multitenant architecture allows for many pluggable databases (PDBs) to be created and users are welcome to create and name their pluggable databases to their liking and for their use cases. As such, the `runOracle.sh` script cannot make a guess as to which database the script(s) should be run in. A user may want for a SQL script to set a parameter at the container database level, or perhaps create a common user or perhaps even create a brand new pluggable database. Or a user may want to run a SQL script in the pluggable database or other pluggable databases that have been created by another script beforehand.
By default, the scripts connect as `SYS` to the Oracle instance (the top-level CDB), because from there the user has full control of what to do next and it also does not require a password to be provided.

The `ALTER SESSION` command is a valid approach.
Another one would be to issue a new `connect` inside the SQL script for SQL*Plus to establish a new connection, e.g.

```sql
conn sys/<password>@//localhost/XEPDB1
```
or 

```sql
conn <my user>/<my password>@//localhost/<my PDB name>
```

Another approach could be to leverage the shell script functionality instead and have that shell script invoke SQL*Plus and run the SQL scripts (or whatever other CLI command).
That way you will not have to touch each individual SQL script file but can establish the connection once and call the scripts directly afterwards (and also in the order that you like).

I hope this helps!

**Comment by rprodan** [comment]
Hello @gvenzl,

first of all, thank you for your answer. 
I will definitely consider your recommendations and thus eliminate unnecessary repeatable code segments. 

As for me this issue can be closed.
