### ISSUE TITLE
Oracle Instant Clienr 21: sqlldr error

### ISSUE THREAD

**Issue by EricPE69** [oracle/docker-images#1910]
I build an Oracle Instant Client docker image (from https://github.com/oracle/docker-images/tree/main/OracleInstantClient - version 21) (Dockerfile is joined)

I can execute sqlplus without problem but with sqlldr I have the following error:
sqlldr: error while loading shared libraries: libomsodm.so: cannot open shared object file: No such file or directory

It works. with Instant Client version 19.

For information libomsodm.so is NOT present in the rpm package: oracle-instantclient-tools-21.1.0.0.0-1.x86_64.rpm
But it is present in the zip package: instantclient-tools-linux.x64-21.1.0.0.0.zip
[Dockerfile21.txt](https://github.com/oracle/docker-images/files/6348725/Dockerfile21.txt)

What is the problem ?

**Comment by cjbj** [comment]
Known issue with the 21.1 RPMs.  It's tracked as Oracle bug 32422414.  It will be fixed by the SQL*Loader team in the next release update.  Until then, use the ZIPs.   I understand the problem was not the missing libomsdom library, but the fact that it shouldn't have been required in the first place. So don't be surprised when the next Oracle Instant Client 21c release doesn't have this library in the ZIP or the RPM.

**Comment by EricPE69** [comment]
Thank you
