### ISSUE TITLE
[ORACLE 18c] Docker Commit of an initialized container

### ISSUE THREAD

**Issue by ortizman** [oracle/docker-images#1931]
**Context**
Execution of Integration test into continuous integration pipelines

**Question**
I want to avoid creating the database in each new instance of the container, since it is costly in terms of time for a CI pipeline.

The first alternative that occurred to me was:

1. Instantiate the XE version on my local machine.
2. Once the database is initialized, do a docker commit of the instance and build a new docker image
3. Use this docker image in my CI pipeline

Am I forgetting something? Do you see any inconvenience in this?

It makes me doubt why it is not done this way in the XE version.

Thanks

**Comment by AmedeeBulle** [comment]
The database files are not in the container itself, they are in a separate volume...

**Comment by ortizman** [comment]
Sure. The point I make is to initialize the database without a mapped volume. In this way everything would be inside the container. Obviously, the data would be lost when destroying the container, but that is what I want to start from a clean base for the integration tests

**Comment by gvenzl** [comment]
Hey @ortizman, have a look at https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance/samples/prebuiltdb how to do that.

The reasons why it isn't done by default are because:
1) Adding the database files to the image itself will make the image bigger and for some reason, a lot of people had a lot of opinions about how big the image(s) already are.
1) The database character set is decided at database creation time and although it can be changed later on it would entail a lengthy character set migration on all the data.
1) for EE and SE2 the `ORACLE_SID` (Oracle instance name) is not fixed and can be decided by the user, however, that can only be done (easily) at database creation (and we wanted to keep the look and feel the same)

**Comment by ortizman** [comment]
that link was exactly what I needed. Thanks
