### ISSUE TITLE
OracleDatabase setPassword.sh works only after first boot for 12.1

### ISSUE THREAD

**Issue by michael-simons** [oracle/docker-images#203]
Hey everybody,

The setPassword.sh scripts fails for me after second run of a container.

Steps to reproduce:

```
docker run --name starterset \
-p 1521:1521 -p 5500:5500 \
-e ORACLE_PDB=STARTERSET \
-v /home/oracle/oradata:/opt/oracle/oradata \
oracle/database:12.1.0.2-ee

docker exec starterset ./setPassword.sh LetsDocker

docker rm starterset

docker run --name starterset \
-p 1521:1521 -p 5500:5500 \
-e ORACLE_PDB=STARTERSET \
-v /home/oracle/oradata:/opt/oracle/oradata \
oracle/database:12.1.0.2-ee

docker exec starterset ./setPassword.sh LetsDockerNotSoMuch
```

`/etc/oratab` doesn't contain any useful entry on second run, so 

```
ORACLE_SID="`grep $ORACLE_HOME /etc/oratab | cut -d: -f1`"
```

in setPassword gives an empty SID and oraenv keeps asking for input.

Also, you should probably use `. oraenv` instead of `source oraenv`, as it is recommended in oraenv for bash.

**Comment by michael-simons** [comment]
I noticed that behavior while developing a workflow with the docker maven plugin.

The stop task removes the container by default.

https://dmp.fabric8.io/#docker:stop

If you / we go the extra mile to keep the database file outside of the container, I expect that the container can be deleted and then created and behave the same, for example like the postgres container does.

**Comment by gvenzl** [comment]
The `runOracle.sh` script now also copies and keeps the `/etc/oratab` file in the volume location fixing the above issue.

Note `.` and `source` are synonymous in bash, i.e they are exactly the same, just like `[` and `test` are.
The reason for using `source oraenv` rather than `. oraenv` is because a `.` can quickly be overlooked, missed or removed while the `source` command is more obvious and transparent.

Thanks a lot for your contribution, happy Dockering. :)
