### ISSUE TITLE
WebLogic 12.2.1.2 -> build.sh errors out because /bin/sh: /u01/oracle/wlst: Permission denied

### ISSUE THREAD

**Issue by nikeneo** [oracle/docker-images#215]
I was trying to build 1221-domain image when I encountered this exception

Step 13 : RUN /u01/oracle/wlst /u01/oracle/create-wls-domain.py &&     mkdir -p /u01/oracle/user_projects/domains/$DOMAIN_NAME/servers/AdminServer/security &&     echo "username=weblogic" > /u01/oracle/user_projects/domains/$DOMAIN_NAME/servers/AdminServer/security/boot.properties &&     echo "password=$ADMIN_PASSWORD" >> /u01/oracle/user_projects/domains/$DOMAIN_NAME/servers/AdminServer/security/boot.properties &&     echo ". /u01/oracle/user_projects/domains/$DOMAIN_NAME/bin/setDomainEnv.sh" >> /u01/oracle/.bashrc
 ---> Running in f9d164a032de
/bin/sh: /u01/oracle/wlst: Permission denied
The command '/bin/sh -c /u01/oracle/wlst /u01/oracle/create-wls-domain.py &&     mkdir -p /u01/oracle/user_projects/domains/$DOMAIN_NAME/servers/AdminServer/security &&     echo "username=weblogic" > /u01/oracle/user_projects/domains/$DOMAIN_NAME/servers/AdminServer/security/boot.properties &&     echo "password=$ADMIN_PASSWORD" >> /u01/oracle/user_projects/domains/$DOMAIN_NAME/servers/AdminServer/security/boot.properties &&     echo ". /u01/oracle/user_projects/domains/$DOMAIN_NAME/bin/setDomainEnv.sh" >> /u01/oracle/.bashrc' returned a non-zero code: 126

**Comment by brunoborges** [comment]
Make sure the script `wlst` is executable in your local host environment prior to build.

**Comment by brunoborges** [comment]
Please post your docker version and host OS:

```
$ uname -a
$ docker -version
```

**Comment by mriccell** [comment]
@nikeneo are you still experiencing the same exception or can I close this issue?

**Comment by mriccell** [comment]
closing issue due to lack of feedback.

**Comment by stasal** [comment]
The problem still exists due to not executable wlst script.
In 12213-domain example Dockerfile there are lines to set executable mode for *.py and *.sh files. But there are no such lines in 12212-domain example.
But these Dockerfiles also need to have execution mode addition for `wlst` file or it should have an .sh extension to fix this problem

**Comment by drishticode** [comment]
For those still facing the issue, check if your docker version is > 17.x. 
If so you might need to add `--chown=oracle:oracle` to the `COPY` command of Dockerfile. 
Otherwise scripts are silently copied as root user resulting in permission denied for the oracle user. 
[Docker reference](https://docs.docker.com/engine/reference/builder/#copy)

**Comment by brunoborges** [comment]
@drishticode maybe you should submit a PR :)

// @gvenzl @mriccell

**Comment by naidukr** [comment]
Hi i am getting the same error


/bin/sh: wlst: command not found
The command '/bin/sh -c wlst -loadProperties /u01/oracle/datasource.properties /u01/oracle/ds-deploy.py &&     wlst /u01/oracle/jms-deploy.py' returned a non-zero code: 127
