### ISSUE TITLE
Edit General_Purpose percentageMemTOSGA Parameter on build

### ISSUE THREAD

**Issue by vbaidak** [oracle/docker-images#2224]
Hi!

I'm getting the following error when creating new PDBs:
```cmd
[WARNING] ORA-04031: unable to allocate 1048848 bytes of shared memory (“shared pool”,”unknown object”,”PDB Dynamic He”,”alls-ktimcem”)
```

According to [this article](https://ahmedfattah.com/2020/01/13/oracle-database-19c-installation-on-oracle-cloud-compute-instance/) I need to change `percentageMemTOSGA` parameter in `General_Purpose.dbc` file, which is by default set to `40`

How this can be done during the build?
> I'm using 12.2.0.1 enterprise version

**Comment by abhisbyk** [comment]
@vbaidak We do not have `percentageMemTOSGA` parameter exposed currently, but you can set SGA and PGA manually using `INIT_SGA_SIZE` and `INIT_PGA_SIZE` options to docker run command. Using these parameters you can give absolute values instead of giving them in percentage form. This should resolve the issue.
More info on these init-parameters is present in the [Readme](https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance#running-oracle-database-in-a-container).

Closing this issue for now. Please reopen if the issue persists.
