### ISSUE TITLE
Create Image without Pluggable Database Feature

### ISSUE THREAD

**Issue by rubenst2013** [oracle/docker-images#229]
Hi, 

Our application is incompatible to the PDB feature in Oracle DB 12c. 

So far my internet searches didn't yield any useful info about disabling that feature.
I only saw a few reference in the Dockerfile and build scripts but I am unsure if commenting them out is enough.

Besides, wouldn't the thought rather be 1 container - 1 database, instead of 1 container and 1 CDB + N PDBs? :)

I appreciate any advice.

**Comment by brunoborges** [comment]
You can't easly port a CDB, but you can easily port a PDB. If you are a Java developer, think of it this way:
Your java app = PDB
JVM = CDB
Then the container itself

**Comment by rubenst2013** [comment]
Hi @brunoborges,

we are java developers :) Though I myself am not and we have just started experimenting with Docker. Sadly our company does not adapt any proprietary DB features to stay DB agnostic. That's why I am having trouble placing PDB at our product management, but I am certainly trying because I see the value in it. 

Also I think I managed to change the DB creation scripts and templates you provided so it initializes without PDB feature. At least our installer was able to create the user and fill the DB with data.
How would I go about giving my findings to this project? Via pull request for the samples?

And thanks again for your continued support! :+1:

**Comment by gvenzl** [comment]
Hi @rubenst2013, 

I think there is a misunderstanding here. The CDB/PDB (Container Database / Pluggable Database) in Oracle 12c is not a feature, it's rather a complete change in the Oracle Database architecture. [Oracle has deprecated the traditional architecture, now referred to as "Non-CDB architecture".](http://docs.oracle.com/database/121/UPGRD/deprecated.htm#BABDBCJI) That means that sooner or later users will have no choice anymore but to use the new CDB architecture.

The good news is that adopting the new architecture should be fully transparent. The only exception is if you are using some of the features which aren't supported in the 12.1 CDB architecture yet. What we have also seen in the past is that connection pools and programs still use the SID rather than the **service name** which is recommended ever since 10g (i.e. early 2000s). Also that would be a reason for not being able to use the CDB architecture (PDBs are only exposed via service names) but there are several ways around that too. Of course we would highly recommend to change to service names as they offer a lot of other benefits that a developer may not see but an Ops guy would be happy to have.
A user in a PDB can do everything a user could do in a non-CDB environment and the user inside the PDB cannot even tell that he is inside a PDB or a non-CDB. So from that point of view you should have no problem running against a PDB. I'm more than happy to help if that is not the case (also outside a Docker environment).
I also think that this invalidates the standpoint of your company as the said CDB architecture is an architecture change rather than a feature add. And again, it should be fully transparent.

To your point of having one container with one database rather than having one container with N PDBs: That is not quite true. PDBs, as you said yourself, offer tremendous benefit also in a Docker environment and even with just one PDB within the CDB. Some of those are:

**Portability**: Even with just one PDB in a container developers can develop against that PDB and once done, unplug that PDB and plug it into any other CDB. That CDB may run in another container, or run on a non-dockerized UAT or testing environment all the way to production. It can also mean that developers can develop against a dockerized PDB which they then unplug and give to their customers to run the latest version of their application against.

**Cloning**: PDBs can be cloned. That means if a colleague of yours has an issue with something but for whatever reason cannot give you access to his Docker container or you cannot recreate the issue, he can simply clone the PDB and unplug it. You can then plug that PDB into your container and see whats going on. Of course the benefits of cloning go even further than that.

**Patching and Upgrading**: If you ever have to patch or upgrade your database with existing data in it, you can do so by just unplugging that PDB and plugging it into a patched or upgraded CDB. The patch or upgrade will be applied automatically on plug-in. Granted, that may not make a huge difference in a simple "give me a DB in a container" example but as soon as you get to databases containing starter sets, etc. this may come in very handy rather than rebuilding the database from scratch.

There are more benefits but those are the big ones that a lot of people are already using out there. Whether or not they are within a Docker environment.

I'm glad to read that you made the Docker build files work for your environment. However, Oracle does not promote functionality once it has been deprecated. That would defeat the whole purpose of deprecation itself. Hence even if you would file a PR with that change, which would be the correct way of doing it, we would not pull it back in. It also means that we won't provide an image with a non-CDB architecture at all and therefore I will close this issue as wontfix.

Of course there are people out there that still want an image of a non-CDB architecture Oracle Database, whether for a legitimate reason or not. Therefore I would ask you to comment on this issue with a link to the changed version that you have made so that people looking for one in the future can benefit from your changes, if that is OK for you.

Thanks,

Gerald
