### ISSUE TITLE
ORA-48189 OS command to create directory failed

### ISSUE THREAD

**Issue by csekme** [oracle/docker-images#2363]
Hi,

If I issue **select * from dba_directories;** I get the following error message ORA-48189 OS command to create directory failed.
Only from PDB but it works from CDB.

After creating a new container the query works well only the first time.
Any further trial results error.

- I tried to set permissions recursively on /diag folder to 777 in the test enviroment.
- I set permissions to 777 on /opt/oracle/oradata folder too

Oracle version 21.3.0 SE
Docker version 20.10.14
OS: Fedora 35 Server (SELinux is disabled)

Thank you in advance

**Comment by abhisbyk** [comment]
@csekme I am unable to reproduce this on my machine.
OS: OL7
Docker version: 19.03
Oracle Database: Oracle 21.3 SE

This issue mostly caused by wrong permissions to `$ORACLE_BASE/diag` folder. It should be 775. 
Can you share more details: your `$ORACLE_BASE/diag` permissions, docker container logs and the entire error that comes while running the command you specified ?
