### ISSUE TITLE
Unable to set ssh.

### ISSUE THREAD

**Issue by macfol** [oracle/docker-images#238]
Hi,

I'm having problem to set ssh on oracle linux in a docker.

I have tried to do so according to [tutorial](https://docs.oracle.com/cd/E18930_01/html/821-2426/gksja.html#gksrd)

When I try  

> /sbin/service sshd status

I get: 

> Failed to get D-Bus connection: Operation not permitted

Appreciate any help

**Comment by Djelibeybi** [comment]
You cannot start OpenSSH inside an Oracle Linux Docker container.

**Comment by macfol** [comment]
Thanks for the information. Generally what I would like to achieve is to create a Docker instance of Oracle DB wich can be connected to via SSH. 
Is there any way to do it?

**Comment by Djelibeybi** [comment]
That's not really how you interact with Docker containers. You SSH into the host running the container, then use Docker commands to interact with the database running inside the container. The only thing that runs inside the container itself is the database.

**Comment by ccasadiego** [comment]
Hi, I'm really sorry for commenting on an old and closed post but currently I'm facing the same issue, the reason I need ssh on the container is because I'm using vagrant and it uses ssh to run all the provisioning commands on the image, where can I find more info about it? have been testing different stuff from stack overflow and other sites but haven't managed to get this running
