### ISSUE TITLE
Unable to start web logic server using container-registry.oracle.com/middleware/weblogic:12.2.1.4-slim image

### ISSUE THREAD

**Issue by JhaSujata** [oracle/docker-images#2508]
I am trying to install weblogic server on ubuntu machine using podman.
 I have executed following commands
>$podman login container-registry.oracle.com
 $podman pull container-registry.oracle.com/middleware/weblogic:12.2.1.4-slim

I created a folder for keeping "domain.properties" file. This file only contains username and password.

>$podman run -d -p 7001:7001 -p 9002:9002 -v /home/sujata/oracle/properties container registry.oracle.com/middleware/weblogic:12.2.1.4-slim

After invoking run, if I check the current status of container through 
> podman ps -a

It shows as exited

I am unable to understand what else I need to set.
Please look into the issue

**Comment by Djelibeybi** [comment]
You are not mapping the `domain.properties` file correctly: you need to provide both the host path and the container path to the `-v` parameter, i.e. it should probably be `-v $HOME/oracle/properties:/u01/oracle/properties` -- your command line is missing the in-container path.

**Comment by JhaSujata** [comment]
Thanks for the response. I corrected the path.
I am trying to open the management console through https://<hostname>:9002/console but unable to access. 
please guide

**Comment by Djelibeybi** [comment]
There's not enough information to even begin to answer why you can't access the console, but that URL isn't valid either. It should probably be `https://localhost:9002/console`. However, without the logs or container output, it's impossible to say.

Also, as your initial problem is resolved, I'm going to go ahead and close this issue. Please review the existing issues (and discussions) to see if anyone else had the same issue fixed before. If you're still stuck, I suggest starting a discussion as your questions are about how to use the images, rather than reporting a bug with an image.
