### ISSUE TITLE
Builded image with 19.3.0 not working

### ISSUE THREAD

**Issue by thekk1** [oracle/docker-images#2525]
If I build an Image with [https://download.oracle.com/otn/linux/oracle19c/190000/LINUX.X64_193000_db_home.zip](LINUX.X64_193000_db_home.zip) from this repo, the init process of the db files are hang at 36% and will not finished.

Build process:
```
git clone https://github.com/oracle/docker-images
cp 19.3.0/LINUX.X64_193000_db_home.zip ./OracleDatabase/SingleInstance/dockerfiles/19.3.0/
cd /OracleDatabase/SingleInstance/dockerfiles
./buildContainerImage.sh -v 19.3.0 -e
docker run -tdi -m 4096m -e INIT_SGA_SIZE=3000 -e INIT_PGA_SIZE=1000 -e ORACLE_PWD=bup -e ORACLE_SID=XE -e ORACLE_PDB=PDB -p 1531:1521 --restart unless-stopped --name ora oracle/database:19.3.0-ee
```

Result:
```
DBCA_PROGRESS : 8%
[ 2022-12-07 11:49:09.380 UTC ] Copying database files
DBCA_PROGRESS : 31%
[ 2022-12-07 11:50:25.969 UTC ] Creating and starting Oracle instance
DBCA_PROGRESS : 32%
DBCA_PROGRESS : 36%

```

**Comment by oraclesean** [comment]
Check `/opt/oracle/diag/rdbms/xe/XE/trace/alert_XE.log` in the container. It shows the normal database restarts that occur during DBCA failing. The associated trace files show memory errors. After removing the `-m` option from your command, DBCA completes normally. This is likely a memory issue caused by setting SGA/PGA to a value nearly equal to the container memory limit, leaving no room for the container to run any other processes.

**Comment by oraclesean** [comment]
When troubleshooting container issues, I recommend isolating the root cause by reviewing the parameters passed to `docker run`, reducing the command to the minimum required to reproduce the error. Also, `-tdi` in the above command is contradictory. `-d` runs the container as a detached process. `-i` and `-t` used together initiate an interactive TTY session.

**Comment by thekk1** [comment]
Thank you for this explanation. I did a mistake here by not realising there is more RAM needed for processes that are not included in SGA and PGA. Removing the -m option resolved the problem.
