### ISSUE TITLE
Checking Docker version(Docker 23.0.0)

### ISSUE THREAD

**Issue by Lyn265** [oracle/docker-images#2556]
in the BuildContrainerImage.sh ,There is a problem with the value of the docker version of 23.0.0?

error message:Docker version is below the minimum required version 17.09.

**Comment by remi9898** [comment]
I got the same error.  It happens because script BuildContrainerImage.sh removes the dots from the version numbers in order to compare simple integers.  In my case, Docker version 23.0 becomes integer 230, and the minimum allowed version of Docker 17.09 becomes integer 1709.  Well, 230 is always less than 1709 so the test fails even though version 23.0 is much higher than 17.09.  Quick workaround is to edit BuildContrainerImage.sh and change the min allowed version from 17.09 to 18.0 or any other 3-digit number.  Longer term, we need to do better than dot removal comparisons.

**Comment by alexsuter** [comment]
Yep. I face the same issue.

**Comment by adanecki** [comment]
As an alternative, we cloud also just get the full version string, which in this case is 23.0.0 and from it remove dots and cut to 4. 
I don't see the point of cutting the first 5 characters from the version string, as then it's compared to 4 digit integer. No matter what will be the integer, it will always be larger than the minimal version 1709.

DOCKER_VERSION=$("${CONTAINER_RUNTIME}" version --format '{{.Server.Version}}'|| exit 0)
DOCKER_VERSION=$(printf "%.4s" "${DOCKER_VERSION//./}")

**Comment by brunos1** [comment]
> 
I just got this same error and have checked the BuildContrainerImage.sh and just realized it solves the problem.
But instead using "%.4s" I just used "%.6s"

**Comment by alexsuter** [comment]
PR is ready. Can we merge it?

**Comment by aditya059** [comment]
Fixed
