### ISSUE TITLE
Startup scripts not being run in Oracle Docker container

### ISSUE THREAD

**Issue by michny** [oracle/docker-images#2590]
I have issues with startup scripts not being run when I start an Oracle docker container.

I have pulled the Docker image `container-registry.oracle.com/database/enterprise:latest` and started it using the command `docker run -d --name oracle-db2 -p 1521:1521 -e ORACLE_PWD=admin1234 -v C:/Source/dummyscripts:/opt/oracle/scripts/startup container-registry.oracle.com/database/enterprise:latest`.
The folder "C:\Source\dummyscripts" contains a SQL script called `01_local-oracle-setup.sql` which executes a `CREATE USER`, `CONNECT` (as that user), `CREATE TABLE` and `INSERT` (into created table) statements. The script works just fine when run through SQL Developer against an oracle container, so I don't imagine there is anything wrong with the script.

Starting the container with the `docker run` shown above successfully starts the container and I can (after some minutes) connect to it using either SQL Developer or SQLPlus with `docker exec -it oracle-db2 sqlplus`.
But it has apparently NOT executed my script from the /opt/oracle/scripts/startup folder. At least the user and table created by the scripts are not to be found.

I don't see any reports of errors when running the `docker run` though, so I am not sure how to verify why it doesn't run my script.
Any help would be greatly appreciated. 

I have also tried using "C:\Source\dummyscripts" (the Windows version with backslash rather than forward slash) as volume, but it makes no difference.

If its of any relevance, I am running on Windows 10 and Docker Desktop for Windows and I am just trying to start the container on my local machine for now.

**Comment by sustacek** [comment]
I'd first check if your .sql actually is in the container:
```
$ docker exec -it oracle-19-oracledb-1 ls -la /opt/oracle/scripts/startup
```

If not, chances are you did not mount your host's directory into the (Linux) VM which runs Docker server for you. This happens a lot to me on Colima on OSX, when I reset it the mounts are empty.

Since you are using Windows, I bet you're running into the same. E.g. if you are using Docker Desktop, make sure the `C:/Source/dummyscripts` is whitelisted and available to the VM running Docker.

**Comment by naberin** [comment]
The image I have tried is `free:latest`, so please note that some things may be different if anything, I would advise you to consult the documentation.

First, you can try running the following command below. For FREEDB, it would display the results of your nit script or if there are any errors. It showed whether it actually ran at all. An example output is showed below:
```bash
$ docker logs mycontainer

# output snippet
Version 23.3.0.23.09
The Oracle base remains unchanged with value /opt/oracle
#########################
DATABASE IS READY TO USE!
#########################

Executing user defined scripts
/opt/oracle/runUserScripts.sh: running /opt/oracle/scripts/startup/init.sql

Session altered.

User created.

Grant succeeded.

Grant succeeded.

Table created.

Table created.

DONE: Executing user defined scripts
```

Another thing to note is you should run alter session to your PDB because the init script would be run against the CDB otherwise. So to do that, initially in your sql script add the following:

```sql
-- note the following is for FREEDB
alter session set container=FREEPDB1; 
```

**Comment by murata-kawairi-business** [comment]
What I encountered was a similar but different pattern.
If I put the script in `init-scripts/startup/` it runs, but if I put it in `init-scripts/setup/` it is ignored.
Both scripts have the `alter session set container = $PDB_NAME;` at the beginning of the run.

Is the root of this problem the same?

If I am out of place, please forgive me.

**Comment by yunus-qureshi** [comment]
If you are running free:latest from container-registry then this is expected. Free comes with a pre-built database and therefore just start up scripts are executed and not setup ones. 
If you however specify a mount for your database, then a fresh Free DB would be created and setup scripts would be executed too.

**Comment by aditya059** [comment]
We have added a note in "Running Scripts After Setup and On Startup" in OCR Free Readme

**Comment by retrography** [comment]
> If you are running free:latest from container-registry then this is expected. Free comes with a pre-built database and therefore just start up scripts are executed and not setup ones. If you however specify a mount for your database, then a fresh Free DB would be created and setup scripts would be executed too.

Unfortunately it does not run setup scripts even when an empty folder is mounted for the databases.

**Comment by yunus-qureshi** [comment]
Can you please attach the pod logs

**Comment by retrography** [comment]
I just moved on, by putting the scripts in startup and checking every time whether this is the first time they are being run. Startup folder works.
