### ISSUE TITLE
Document how to set the Oracle timezone

### ISSUE THREAD

**Issue by neerolyte** [oracle/docker-images#260]
I spent a while chasing the best way to set the DB timezone, but it seems like simply configuring the timezone for the OS when running a container for the first time works great:

```
docker run -t -e "TZ=Australia/Sydney" --name "$name" oracle/database:12.1.0.2-ee
```

It'd be great to note this in the readme.

**Comment by brunoborges** [comment]
Hi @neerolyte, there are many... **many** variables that can be done that way. And they are all documented at docs.oracle.com. Therefore I see no need to document this one (which would imply we should document all of them). @gvenzl do you agree?

**Comment by gvenzl** [comment]
I tend to agree with you, Bruno. A quick Google search of "oracle database 12c set timezone" brings a first hit of "[Datetime Data Types and Time Zone Support - Oracle Help Center](https://docs.oracle.com/database/121/NLSPG/ch4datetime.htm#NLSPG004)" which covers a lot more than just time zones.

Note, the above will set the database timezone only during database creation which only happens if there are no data files in the volume yet. If somebody ought to remove the container and create a new container with just restarting the database with the data files of the volume, this won't have any effect.

The command that one should execute instead would be `ALTER DATABASE SET TIME_ZONE='Europe/Vienna';` 
But then there is also the option to just change the time zone per session/connection: `ALTER SESSION SET TIME_ZONE='America/Los_Angeles';`

So, back to what Bruno said, there are many variables and many ways how to do things. Documenting all would almost be like replicating the online documentation.

But, thanks to this issue logged, people with that question can now just search through issues and find this thread which will hopefully allow them a quick turnaround.

**Comment by neerolyte** [comment]
No worries, fwiw `ALTER DATABASE SET TIME_ZONE...` didn't seem to be updating `SYSDATE` for me and altering the session timezone was impractical as I'm supporting legacy code that's using `SYSDATE` instead of `CURRENT_DATE`.

I agree that having the issue here is sufficient doco.

**Comment by gvenzl** [comment]
`ALTER DATABASE SET TIMEZONE` requires a DB restart. Perhaps that's why you didn't see SYSDATE changing?!

**Comment by neerolyte** [comment]
Pretty sure I tried stuff like:

```
ALTER DATABASE SET TIMEZONE = 'Australia/Sydney';
shutdown immediate;
startup;
```

but I deleted all my scratch notes from the timezone stuff when I finally got a solution that was working.

I'm no Oracle DBA, so I'm almost certainly doing something wrong :)

**Comment by gvenzl** [comment]
That's fine, as long as you have it working now. :)
