### ISSUE TITLE
Oracle Database running on Apple Silicon

### ISSUE THREAD

**Issue by doberkofler** [oracle/docker-images#2613]
I have been running Oracle Databases on Apple Silicon using Colima with the Qemu VM for quite a while now and it generally does work but the performance is not really what it used to be when running Docker Desktop on an Intel processor.
I still hope that Oracle will finally support ARM and we (Apple Developers) will be again have the full power of the Database on our new Apple computers.
Has someone any news on if and when Oracle Database will be natively running on Apple Silicon? 
Has someone been able to run an Oracle Database on Apple Silicon using Docker Desktop?
What is the current recommendation when running Colima especially regarding the vm type?

**Comment by yunus-qureshi** [comment]
@doberkofler can you try if the following steps work for you

1.  brew install podman lima
2.  Install Java from https://download.oracle.com/java/20/latest/jdk-20_macos-aarch64_bin.dmg
3.  Install SQLcl https://download.oracle.com/otn_software/java/sqldeveloper/sqlcl-latest.zip
4.  limactl start --name podman-amd64  --set='.arch = "x86_64" | .memory = "10GiB"'  template://podman
5.  Wait for VM to boot up. Above cmd may error out if the VM takes a while to boot up. Ultimately it comes up fine and you can even ssh into it
6.  export CONTAINER_HOST=unix://Users/$USER/.lima/podman-amd64/sock/podman.sock
7.  podman pull container-registry.oracle.com/database/free:latest
8.  podman run -e ORACLE_PWD=<> -d -P container-registry.oracle.com/database/free:latest
9.  From sqlcl installed in #3, run sqlcl/bin/sql sys/<ORACLE_PWD>@localhost:<PORT>/FREE as sysdba
 
Steps #2 and #3 are needed to get a Java based SQL client on Apple M1 due to unavailability of native SQL client.

**Comment by doberkofler** [comment]
Thank you for your feedback, but it raises a few new questions:
- Are you suggesting the use of podman instead of colima?
- Are there any specific reasons/advantages for using podman compared to colima?
= Did you find padman faster than colima although and coukd you provide some numbers?
- Is it still not possible to use Docker Desktop and can  you elaborate kn why?
= Is there still no information on native support of Oracle Databases on ARM / Apple Silicon?
Thank you!

**Comment by cjbj** [comment]
> Apple M1 due to unavailability of native SQL client.

SQL*Plus x86_64 works nicely via Rosetta.

**Comment by yunus-qureshi** [comment]
This is now documented in FAQ
