### ISSUE TITLE
Need some assistance for running Oracle Database on dockers

### ISSUE THREAD

**Issue by kybrix** [oracle/docker-images#2667]
I am bit new to dockers for Oracle DB and have few questions:

1)For the Quarterly patches /one-off patches, do I need to apply them using Opatch apply similar to on-prem dbs , eg copying files internally and then do an Opatch apply there? or 

Do I need to apply the patch on the base image, create a new image and then run the docker container??

2) When i create a new image from the base image after applying patches, what is the recommended process for the data?? 
  a) Will I have to export/import the data every time or
  b) Do I have to use unplug/plug pdb feature of the DB container
  c) or is there a way to use  the existing db files rather than creating a new DB every time when you run a new image??

3) Has anyone seen any issues with larger DBs having many blobs running on dockers??

4) How can I use Kubernetes for the docker orchestration for Oracle db??

5) Also regarding licenses on dockers?? Does it tie with the docker or the infra on which the docker is running?

Thanks in advance for your time and support

**Comment by kybrix** [comment]
Thanks it was really helpful.

for the volume-related question, will it work for the new container image or can I use the plug/unplug option there??

I will try an update.

**Comment by kybrix** [comment]
Thanks Sean for the information.

My question  was on the database image download. For creating my own image with patches, I would need to download binaries.

So do i need to download normal db binaries from edelivery and then put it in the Singleinstance folder or do i need to download it from the container portal (https://container-registry.oracle.com/)??

In case from container repository from oracle then there is no option to get a zip file from there. I can only pull images from the Oracle container repository via dockers and not a zip file.

Sorry for lame questions :-)

**Comment by oraclesean** [comment]
Ah, I understand now! Thanks for clarifying!

Correct—patched images aren't available in the container registry. You need to download the installation file from the [Oracle Database download page](https://www.oracle.com/database/technologies/oracle-database-software-downloads.html) and place it into the `./dockerfiles/[version]` directory.

You can also get these from the eDelivery site; however, the file names will differ. The `dbInstall.sh` script expects the name and checksum of the installation file to match those from the database downloads page, not eDelivery, so you may need to be creative and either update the script or rename the file.

Patches are only available from My Oracle Support (MOS): https://support.oracle.com. You'll place those files into the `patches` subdirectory.

And questions like yours are great—they help those who develop and maintain repositories understand the real-world needs and challenges people encounter, leading to improved code and documentation. What you asked yesterday prompted me to think of all the ways of getting data "out" of a volume-less container, something I probably wouldn't have considered otherwise, and I'll develop it into a blog post.

**Comment by kybrix** [comment]
Thanks a lot that makes sense. I will try different ways and see..

I found a way to copy image out of the docker into zip file. So will try that as well.

**Comment by kybrix** [comment]
so i have already downloaded 19.3.0 from edelivery . Where is the dbInstall.sh located as I am not find any in the cloned repository??

**Comment by oraclesean** [comment]
Sorry, it's `installDBBinaries.sh` under the version directory.

**Comment by kybrix** [comment]
thanks.. 

One last question

What is the difference between

1) Applying the opatch when DB is already running on docker. Like the container is running and we can then apply patch normally as we do on VMs by copying it inside the location where docker can access and then apply it .
or
2) By creating a new image using BuildContainerImageUtility and then applying the patch
