### ISSUE TITLE
Oracle-Xe image on Dockerhub

### ISSUE THREAD

**Issue by xenoterracide** [oracle/docker-images#273]
Since this is an official dockerfile is there any reason an image can't be pushed to dockerhub?

**Comment by Djelibeybi** [comment]
The Oracle Standard Terms & Conditions do not permit you to share Oracle binaries on any platform. That's why we provide these Dockerfiles: so that you can build your own image after downloading the software in an approved way.

If you want pre-built Docker images that include Oracle proprietary software, please check the Oracle Container Registry at https://container-registry.oracle.com.

**Comment by xenoterracide** [comment]
Thanks, I didn't know about the registry

**Comment by steve-taylor** [comment]
> The Oracle Standard Terms & Conditions do not permit you to share Oracle binaries on any platform.

Do the T&Cs also prevent Oracle from sharing its own binaries?
