### ISSUE TITLE
Add Encryption and/or TLS functionality to Oracle Database

### ISSUE THREAD

**Issue by montge** [oracle/docker-images#276]
If I'm reading the Dockerfiles for Oracle Database, they currently use unencrypted transport.  Could you provide support for Encryption or TLS, or at least a recommended sample.  Ideally we would provide PEM (or JKS if absolutely necessary) formatted files for the Certificate, Key, and Chain, as well as the authorized chains.  This would then be used to load up a service on port 2484 (or similar) that is encrypted.

Alternatively the native encryption might be utilized also.

**Comment by gvenzl** [comment]
Which kind of encryption are you referring to? Do you mean SQL*Net based encryption provided by the Oracle Database or encryption provided via the Docker stack?

**Comment by brunoborges** [comment]
Closing due to no response.

**Comment by galzetta** [comment]
@brunoborges I'm pretty sure @montge meant Oracle encryption. In my case in dev environment we have an Oracle docker DB and we'd like to use Oracle encrypted connection because we have that in production (using a "proper" Oracle server machine in that case). 

Is there a way to enable this on these container images?

**Comment by brunoborges** [comment]
I suggest you open a new issue. I'm no longer at Oracle.
