### ISSUE TITLE
Use camelCase when specifying responseFile parameter during install

### ISSUE THREAD

**Issue by stanpalatnik** [oracle/docker-images#288]
The current call to `runInstaller` tries to pass the `responseFile` parameter in all lower case. The script will reject it. https://github.com/oracle/docker-images/blob/master/OracleDatabase/dockerfiles/12.1.0.2/installDBBinaries.sh#L54

This happens when trying to run the Oracle 11x installer. I was using this file since no one bothered to provide a template for the 11.x versions. Even if this is supported in the 12.x versions, it should still be fixed.

**Comment by gvenzl** [comment]
The Oracle Universal Installer parameter syntax check has changed between 11.2 and 12.1 to allow case insensitive parameters. As 11gR2 is out of premium support and 12cR2 is planned to be released soon, we do not plan on providing 11gR2 Docker build files, except for Express Edition.

**Comment by stanpalatnik** [comment]
Such an Oracle response. Fail

**Comment by brunoborges** [comment]
Hi @stanpalatnik,

We appreciate your interest in running Oracle DB 11gR2 on Docker containers, but we believe that customers who want to use this new approach (DB on container) should do so with the latest versions of the database to guarantee they get the best support possible, since these are versions that still have Premium Support. The same decision was made for WebLogic 11g and other products as you can see in the directory.

Not "such an Oracle response", but an honest one. I hope you understand it, and appreciate the transparency.

Thank you
