### ISSUE TITLE
can not start glassfish 4.1.1 

### ISSUE THREAD

**Issue by robertorgarcia** [oracle/docker-images#334]
when trying to run the glassfish image I'm getting the following error:
WARNING: Can not start bundle file:/glassfish4/glassfish/modules/core.jar because it is not contained in the list of installed bundles

**Comment by fobbyal** [comment]
https://hub.docker.com/u/payara/?__hssc=229474563.1.1490906619316&__hstc=229474563.148a81d767624fdac19d16291cb0aec5.1490906619315.1490906619315.1490906619315.1&__hsfp=4162778173&hsCtaTracking=916ae074-a75f-4aec-87d6-25cf09005c9a%7C92cc9f55-20a7-48c8-9d83-d36ddb23980b

**Comment by aribandy** [comment]
Hi Roberto ,
I checked that it's nothing to do with docker image of Glassfish 4.1.1 . We get the same WARNING in GlassFish 4.1.1 in non dockerized environment as well i.e if we download glassfish 4.1.1 from http://download.oracle.com/glassfish/4.1.1/release/glassfish-4.1.1.zip and start it using 
asadmin start-domain -v . However both in case of dockerized glassfish 4.1.1 and non dockerized glassfish 4.1.1 , in spite of this WARNING glassfish starts up successfully .
Please let us know if you can run glassfish 4.1.1 image runs successfully in spite of this WARNING .

**Comment by aribandy** [comment]
We have done some further analysis .Its happening because we have an entry in osgi.properties but did not remove it from packaging. Note that this is seen on 5.0 as well. It's a GlassFish product issue not a GlassFish docker issue .Though this is a harmless warning , we have created a GlassFish product issue (https://java.net/jira/browse/GLASSFISH-21714) for this . As glassfish 4.1.1 image runs successfully(if Roberto confirms that) , we can close the docker issue .

**Comment by robertorgarcia** [comment]
thanks everyone, my issue was that I had setup a memory limit on the container so the container couldn't finish loading
