### ISSUE TITLE
Cannot log on as user

### ISSUE THREAD

**Issue by ja6a** [oracle/docker-images#443]
Having created an Oracle 12.2.0.1 ee image I am running it. I am trying to log in as a newly created user but I am unable to do so. I am using sqlplus locally.

Commands:
```
SQL> create user fred identified by fred;

User created.

SQL> conn fred/fred;
ERROR:
ORA-01017: invalid username/password; logon denied


Warning: You are no longer connected to ORACLE.
```
Notes: 
Image created with the following command:
docker run --name myDB \
-p 1521:1521 -p 5500:5500 \
-e ORACLE_SID=my \
-e ORACLE_PWD=my_password \
oracle/database:12.2.0.1-ee

My environment is Windows 7, Docker Toolbox.

**Comment by gvenzl** [comment]
Hi @ja6a, on which database are you logged on? I think the issue is a misunderstanding. I believe that you created user `fred` in the PDB (because CDB common users have to have `C##` as a prefix) but when you issue a `conn user/pwd` without a connection identifier you get connected to the default database, i.e. `ORACLE_SID` which happens to be the CDB:

> SQL*Plus does not prompt for a service name, but uses your default database if you do not include a connect identifier. http://docs.oracle.com/database/122/SQPUG/CONNECT.htm#SQPUG036

```
--- Connected on the CDB (no connection identifier specified)
[oracle@7f06aa711405 ~]$ sqlplus / as sysdba

SQL*Plus: Release 12.2.0.1.0 Production on Wed Jul 5 16:26:13 2017

Copyright (c) 1982, 2016, Oracle.  All rights reserved.


Connected to:
Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production

--- Can't create common user fred on CDB level because it doesn't have "C##" as a prefix.
SQL> create user fred identified by fred;
create user fred identified by fred
            *
ERROR at line 1:
ORA-65096: invalid common user or role name

-- Connect at PDB level
SQL> conn sys/LetsDocker@//localhost:1521/ORCLPDB1 as sysdba
Connected.
SQL> create user fred identified by fred;

User created.

-- Issue conn without connection identifier
SQL> conn fred/fred
ERROR:
ORA-01017: invalid username/password; logon denied


Warning: You are no longer connected to ORACLE.

-- Issue conn with connection identifier to the PDB, now we see that the user actually exists but lacks the CREATE SESSION privilege.
SQL> conn fred/fred@//localhost:1521/ORCLPDB1
ERROR:
ORA-01045: user FRED lacks CREATE SESSION privilege; logon denied
```

**Comment by gvenzl** [comment]
Closing issue due to no response.

**Comment by ja6a** [comment]
Sorry for the lack of response. I don't have anytime to devote to this. I remember that the problem started after I issued the following commands:
`ALTER SYSTEM SET DB_CREATE_FILE_DEST='/home/oracle' SCOPE=SPFILE;
ALTER SYSTEM SET SEC_CASE_SENSITIVE_LOGON=FALSE SCOPE=BOTH;
ALTER SYSTEM SET PROCESSES=500 SCOPE=SPFILE;
ALTER SYSTEM SET SESSIONS=500 SCOPE=SPFILE;
ALTER SYSTEM SET DB_FILES=1000 SCOPE=SPFILE;
ALTER SYSTEM SET NLS_LENGTH_SEMANTICS=CHAR SCOPE=BOTH;`
and then restarted the container.

**Comment by gvenzl** [comment]
You should certainly **not** change the `DB_CREATE_FILE_DEST` parameter to `/home/oracle` as this will create new data files inside the container rather than within the volume.
Also, as I tried to point out above I believe that your issue is simply that you do not provide a connect identifier when connecting with your user.
Anyway, once you have some time please go through the recommendations please try to reproduce the issue and reopen this ticket if needed.

**Comment by MatosDimitris** [comment]
ALTER SYSTEM SET SEC_CASE_SENSITIVE_LOGON=FALSE
This is the problem
I had exactly the some issue, and I lost one whole day!

**Comment by gvenzl** [comment]
If setting this **deprecated** parameter to FALSE your problem merely is that the password you used is specified in an case insensitive manner while the database uses case sensitive passwords.

You will find in the [docs that this parameter is deprecated](http://docs.oracle.com/database/122/REFRN/SEC_CASE_SENSITIVE_LOGON.htm#REFRN10299) which means you really should change your app to allow case sensitive passwords because sooner or later that parameter may disappear.

**Comment by MatosDimitris** [comment]
I Have done this and everything is ok now
SQLNET.ALLOWED_LOGON_VERSION_SERVER=10 (or11) to sqlnet.ora ans after restart you recreate the passwords and and is working the SEC_CASE_SENSITIVE_LOGON = FALSE;

**Comment by sparky-streamsets** [comment]
I'm still not able to get this to work.

Environment: Oracle 12c Enterprise running on Docker in Ubuntu

tnsping orclpdb1
Attempting to contact (DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = 0.0.0.0)(PORT = 1521)) (CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = ORCLPDB1.localdomain)))
OK (0 msec)

I've tried connecting in and outside of the docker container using SQL*Plus. I've tried using the suggestion to turn off case sensitivity in the login, I've tried recreating my local user several times, I've granted it CONNECT, RESOURCE, DBA, and CREATE SESSION. No matter what I do, I keep getting ORA-01017 errors.

I've tried the following passwords: password, PASSWORD, Password, and Password_1. I've tried using double quotes, single quotes and no quotes around the password in the ALTER USER statement.

So far, the only user I can use to log in successfully is sys:

sqlplus sys/Oradoc_db1@//localhost:1521/ORCLPDB1.localdomain as sysdba
works
sqlplus AQ_ADMIN/Password@//localhost:1521/ORCLPDB1.localdomain
doesn't work
