### ISSUE TITLE
SID, PDB, tnsnames, and db_name confusion

### ISSUE THREAD

**Issue by normenmueller** [oracle/docker-images#480]
Running

    #!/bin/bash
    docker run --name oracle12c \
      -p 1521:1521 \
      -p 5500:5500 \
      -e ORACLE_SID=ang \
      -e ORACLE_PWD=oracle \
      -e ORACLE_PDB=adb \
      -v ${HOME}/env/oracle/data:/opt/oracle/oradata \
      -v ${HOME}/tmp/:${HOME}/tmp/ \
      oracle/database:12.1.0.2-ee

Results in `~/env/oracle/data/dbconfig/ang/tnsnames.ora`:

    ang=localhost:1521/ang
    adb= 
    [1]
    (DESCRIPTION = 
      (ADDRESS = (PROTOCOL = TCP)(HOST = 0.0.0.0)(PORT = 1521))
      (CONNECT_DATA = (SERVER = DEDICATED)(SERVICE_NAME = adb)
                                                          [2]
      )
    )

Why does `ORACLE_PDB` become a TNS alias [1]?
Why does `ORACLE_PDB` become a SERVICE_NAME [2]?

What has to go into "my" tnsnames.ora at `/Applications/oracle/product/instantclient_64/12.1.0.2.0/network/admin/`? At the moment I just adapt:

    ABACUS=
      (DESCRIPTION=
        (ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521))
        (CONNECT_DATA=(SERVER=dedicated)(SERVICE_NAME=ABACUS)))

The other thing that confuses me is the `db_name`:

    $ sqlplus sys/oracle@//localhost:1521/ang as sysdba
    SQL> select name, value from v$parameter where name = 'db_name';
    NAME		VALUE
    --------------------------
    db_name		ang

Why does `ORACLE_SID` become `db_name` rather than ORACLE_PDB?

**Comment by gvenzl** [comment]
Hi @normenmueller,

You can only connect to a pluggable database from the outside world via its service name which is automatically created when the PDB is created. To allow connecting via TNS (@PDB_NAME) we create a TNSNAMES entry for the PDB that points to the service name that is the same as the PDB name.

[`DB_NAME`](http://docs.oracle.com/database/122/REFRN/DB_NAME.htm#REFRN10041) is a database parameter specifying the database name of the container database. That's why the `DB_NAME` parameter is the same as the `ORACLE_SID`.

**Comment by gvenzl** [comment]
Closing this issue as an answer has been provided.

**Comment by normenmueller** [comment]
Hi @gvenzl 

Thanks for your reply! Just for a clear understanding:

>You can only connect to a pluggable database from the outside world via its service name which is automatically created when the PDB is created.

That is, the value of `ORACLE_PDB` is used for the service name. Right?

>To allow connecting via TNS (@PDB_NAME) we create a TNSNAMES entry for the PDB that points to the service name that is the same as the PDB name.

In order to connect via TNS, is the `tnsnames.ora` at, for example, `/Applications/oracle/product/instantclient_64/12.1.0.2.0/network/admin/tnsnames.ora` required?

Or let me re-phrase my question, how do the two `tnsnames.ora` files have to correlate? 

`${HOME}/env/oracle/data/dbconfig/<sid>/tnsnames.ora`:
```
ang=localhost:1521/ang
<ORACLE_PDB>=
^^^^^^^^^^^ [3]
  (DESCRIPTION = 
    (ADDRESS = (PROTOCOL = TCP)(HOST = 0.0.0.0)(PORT = 1521))
    (CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = <ORACLE_PDB>)))
                                                          ^^^^^^^^^^^ [4]
```

`/Applications/oracle/product/instantclient_64/12.1.0.2.0/network/admin/tnsnames.ora`:
```
abacus=
^^^^^^^ [1]
  (DESCRIPTION=
    (ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521))
    (CONNECT_DATA=(SERVER=dedicated)(SERVICE_NAME=abacus)))
                                                  ^^^^^^ [2]
```
[1] is a TNS alias. I guess here I choose whatever I like. So if I connect via SQL*Plus, I could use [1] in order to connect. `sqlplus <username>@[1]`. 

[2] must be equal to [3]?

What is the restriction on [4]? This --- in your docker setup --- must be the value of `ORACLE_PDB`? That is, basically, I could choose for [3] what ever I want, adapt [1] and [2] accordingly, but [4] is "fixed"?

Sorry for keep on asking, but I'd realy like to understand.

**Comment by gvenzl** [comment]
Hi @normenmueller,

> That is, the value of `ORACLE_PDB` is used for the service name. Right?

No, the value of `ORACLE_PDB` is used for the PDB name that you specify in the `CREATE PLUGGABLE DATABASE` statement. That in itself creates a service with equal name, which happens since the days of 10g and has nothing to do with PDBs. Oracle automatically creates a service name corresponding to the database name.

_The  tnsnames.ora file is a configuration file that contains network service names mapped to connect descriptors for the local naming method, or net service names mapped to listener protocol addresses._

Yes, you can specify [1] and [3] to whatever you like but in the end it has to point to some service name that you want to connect to. Whether that service name points to the CDB or the PDB or you create a custom service name even is entirely up to you. If all you try to do is to connect to the PDB then all you need is to leave the SERVICE_NAME entry the same as the ORACLE_PDB name that you have specified or defaulted to. But the network service name [1] / [3] can be whatever you like.

You can also have as many tnsnames.ora files as you like, in the end the client will search for a path specified in `$TNS_ADMIN`, then in `$ORACLE_HOME/network/admin` and then in `$PWD/network/admin` of the client libraries.

For more information around tnsnames.ora and more around network services, have a look at the [Database Net Services Reference](http://docs.oracle.com/database/122/NETRF/local-naming-parameters-in-tnsnames-ora-file.htm#NETRF007).

**Comment by cjbj** [comment]
> the client will search for a path specified in $TNS_ADMIN, then in $ORACLE_HOME/network/admin and then in $PWD/network/admin of the client libraries.

Little known trivia: the files `/etc/tnsnames.ora` and `$HOME/.tnsnames.ora` (with leading period) are in the search path too.  You can see this if you `strace` SQL*Plus.
