### ISSUE TITLE
weblogic 1221-multihost sample: usage of inner-scripts unclear

### ISSUE THREAD

**Issue by multikoop** [oracle/docker-images#52]
Looking at the 12.2.1 Multihost Example
https://github.com/oracle/docker-images/tree/master/OracleWebLogic/samples/1221-multihost

the usage of the inner-scripts/* files is unclear. 

a) Is it just sth left from the oracle nosql example?
b) Can we remove these files here? ( inner-scripts/* )

**Comment by acarlson1994** [comment]
Have these files been removed because multihost is not supported? As it is stated in the documentation:
https://docs.oracle.com/middleware/1221/wls/DOCKR/configuration.htm#DOCKR148

Both the comment above, and commit attached do not explain enough IMO.

Is there any plan for supporting multihost?
Or does multihost work relatively fine, but just isnt officially supported?

**Comment by Djelibeybi** [comment]
This is is closed (and has been for 4 years now). Please open a new issue for your question.
