### ISSUE TITLE
Errors while building and using 12.1.3 image

### ISSUE THREAD

**Issue by z8manu8z** [oracle/docker-images#571]
Hello all,

While building 12.1.3 image, I'm getting the following error : 
`Step 8/11 : RUN $JAVA_HOME/bin/jar xf /u01/$FMW_PKG &&     mv wls12130/* $ORACLE_HOME && rmdir wls12130 &&     cd $ORACLE_HOME &&     sh configure.sh -silent &&     find $ORACLE_HOME -name "*.sh" -exec chmod a+x {} \; &&     rm /u01/$FMW_PKG
 ---> Running in 49bb41931ea5
configure.sh: line 16: hostname: command not found`

But build ends successfully.

Later, when extending oracle/weblogic:12.1.3-developer image with sample 1213-domain sample, I have other errors :
- I can't set PRODUCTION_MODE argument : in step 9 = wlst script, the output is empty (`production_mode : []`)
- Line 59 of Dockerfile, cp fails : permission denied in /u01/oracle/wlserver/common/bin/

Thanks for your help !

Manu

**Comment by tiagolpadua** [comment]
did you found any workaround? trying to build an 12.1.3-developer docker image but im stuck in the "cp fail" error...

**Comment by tiagolpadua** [comment]
I have found some work arounds:

- I can't set PRODUCTION_MODE argument : in step 9 = wlst script, the output is empty (production_mode : [])
In /OracleWebLogic/samples/1213-domain/container-scripts/create-wls-domain.py, around line 15, fix the variable value of "production_mode":
# production_mode         = os.environ.get("PRODUCTION_MODE", "prod")
production_mode = 'dev'

- Line 59 of Dockerfile, cp fails : permission denied in /u01/oracle/wlserver/common/bin/
The problem is because the target file is owned by root, change user to root to execute the command in /OracleWebLogic/samples/1213-domain/Dockerfile:

WORKDIR /u01/oracle
RUN /u01/oracle/wlst /u01/oracle/create-wls-domain.py && \
    mkdir -p /u01/oracle/user_projects/domains/base_domain/servers/AdminServer/security && \
    echo "username=weblogic" > /u01/oracle/user_projects/domains/base_domain/servers/AdminServer/security/boot.properties && \ 
    echo "password=$ADMIN_PASSWORD" >> /u01/oracle/user_projects/domains/base_domain/servers/AdminServer/security/boot.properties && \
    echo ". /u01/oracle/user_projects/domains/base_domain/bin/setDomainEnv.sh" >> /u01/oracle/.bashrc && \ 
    echo "export PATH=$PATH:/u01/oracle/wlserver/common/bin:/u01/oracle/user_projects/domains/base_domain/bin" >> /u01/oracle/.bashrc

USER root
RUN cp /u01/oracle/commEnv.sh /u01/oracle/wlserver/common/bin/commEnv.sh

USER oracle
RUN rm /u01/oracle/create-wls-domain.py /u01/oracle/jaxrs2-template.jar 

p.s.: After this the script runs without problems, but I am not a experienced docker user.

**Comment by mriccell** [comment]
@tiagolpadua thanks for your input I will create a PR with the appropriate fixes
