### ISSUE TITLE
Question: How to start the db after installation is complete?

### ISSUE THREAD

**Issue by DrStrangepork** [oracle/docker-images#634]
I am trying to use the Oracle 12c R2 image as a base db image for our local dev db. The oracle/database:12.2.0.1-se2 image as built results in an image that is 13.3GB, so I want to squash it (`docker export --output="db.tar" db; docker import db.tar db-raw:latest`). When I do I get an image that is only 6.39GB. This is necessary because many developers have to pull this image from our repository over VPN, and even the 6.39GB image pulled from the repo takes ~2 hours, so the oracle/database:12.2.0.1-se2 image would take >4 hours to pull.

My problem is if I run the db-raw:latest image from above, the entire installation process starts over again. What I want is just to have Oracle start. With the existing configuration.

**Comment by gvenzl** [comment]
If you want to just have an Oracle database within the Docker image ready to go, please follow the instructions outlined here: https://github.com/oracle/docker-images/tree/master/OracleDatabase/samples/prebuiltdb

Note, the `./buildDockerImage.sh` script does support squash too. Just add `-o --squash`, e.g. `./buildDockerImage.sh -e -v 12.2.0.1 -o --squash`

**Comment by DrStrangepork** [comment]
The way we install our database is via a java process that opens 1521 to the db container and executes a 325M SQL file. So the database has to be completely self-contained within the container, not mounted via `-v`, and must persist across the process of committing the running db container and starting it up elsewhere.

**Comment by gvenzl** [comment]
Hey @DrStrangepork, so what you are saying is that you want an image that already has a database inside it ready to go, right? As part of the image?

See, the trouble you run into is that when you issue a `docker export` Docker will export everything from within the image **but it will not** export any data from any volume:

[docker export](https://docs.docker.com/engine/reference/commandline/export/#extended-description)
> Extended description
> The docker export command does not export the contents of volumes associated with the container. If a volume is mounted on top of an existing directory in the container, docker export will export the contents of the underlying directory, not the contents of the volume.

So although you might think that you do have everything exported, all the data files remain happily in the volume and don't go into the image. And when you startup the newly imported image it will figure out that there are no data files and start the database setup all over again.

I believe that what you are asking for is exactly what it described in the prebuilt s what's demonstrated in the prebuiltdb sample: Get rid of the `VOLUME` instruction, build the image, install/setup whatever it is that you want, and then export a new DB image. Now, that the `VOLUME` instruction is no longer in there, you can happily issue `docker export` and it will export all the files you wanted to begin with.

You can of course also just create a new Dockerfile, base it on the Oracle Database image and just perform the setup of the database and setup of your scripts. It's a bit more elegant than using export/import but the main issue remains the same: You first have to get rid of that `VOLUME` instruction because once it is in there in an image, there is no way to get rid of it anymore.

**Comment by gvenzl** [comment]
Closing due to lack of response.
