### ISSUE TITLE
Got minus one from a read call

### ISSUE THREAD

**Issue by dstrdstr** [oracle/docker-images#654]
I run docker with command

`docker run --name plugpdb -p 32767:1521 -p 32766:5500 -e ORACLE_SID=DEVOPSUATCDB -v /home/oracle/oradata:/opt/oracle/oradata store/oracle/database-enterprise:12.2.0.1`

in tnsnames.ora I have

`ORCLCDB=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=127.0.0.1)(PORT=32767))
    (CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=ORCLCDB.localdomain)))`
`ORCLPDB1=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=127.0.0.1)(PORT=32766))
    (CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=ORCLPDB1.localdomain)))`

I can connect to ORCLCDB via sqlplus and Oracle SQL Developer, but when I try to connect to ORCLPDB1 I get error:

> An error was encountered performing the requested operation:
>Got minus one from a read call, connect lapse 2 ms., Authentication lapse 0 ms.
>Vendor code 17002

What is wrong?

**Comment by gvenzl** [comment]
Actually, I don't believe that you can connect to `ORCLCDB`. You might be able to start SQL*Plus but connect to an idle instance. The reason why I say this is because you specified your `ORACLE_SID=DEVOPSUATCDB` so there is no `ORCLCDB` database instance running.
Furthermore, I don't think that your database creation was successful altogether because the ORACLE_SID can't be longer than 8 characters and your SID has 12.

Please verify that your database creation has been successful, see the [README.md](https://github.com/oracle/docker-images/blob/master/OracleDatabase/README.md) for further information.
