### ISSUE TITLE
How to Get Oracle Linux 7.x Container  Image  running ??

### ISSUE THREAD

**Issue by github-suresh** [oracle/docker-images#669]
We are not able to work with Linux 7 images
FROM container-registry.oracle.com/os/oraclelinux:7.3

container_linux.go:265: starting container process caused "exec: \"/scratch/cloud805/container-scripts/test.sh\": stat /scratch/cloud805/container-scripts/test.sh: no such file or directory"
docker: Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "exec: \"/scratch/cloud805/container-scripts/test.sh\": stat /scratch/cloud805/container-scripts/test.sh: no such file or directory".

**Comment by github-suresh** [comment]
FROM container-registry.oracle.com/os/oraclelinux:7.3
RUN mkdir -p /scratch/cloud805
ADD container-scripts /scratch/cloud805/container-scripts
RUN chmod -R 777 /scratch/cloud805
WORKDIR /scratch/cloud805/container-scripts
CMD ["test.sh"]

**Comment by github-suresh** [comment]
test.sh  has simple echo as below.

#!/bin/ksh
echo "Test"

**Comment by Djelibeybi** [comment]
You're trying to run `/bin/ksh` but that doesn't exist by default in any Oracle Linux image. I would suggest using `/bin/bash` instead, which is the default shell.

Also, you should not be using `oraclelinux:7.3` because it is old and has known security vulnerabilities. You should switching to using `FROM oraclelinux:7-slim` instead which is always kept up-to-date.

**Comment by Djelibeybi** [comment]
Note that you do not need to use the Container Registry for Oracle Linux images either. They are published as official images on the Docker Hub, so `FROM oraclelinux:7.3` or better yet, `FROM oraclelinux:7-slim` would work too.
