### ISSUE TITLE
OracleDatabase - loadjava giving error 'noclassdeffounderror'

### ISSUE THREAD

**Issue by mehtaanshul22** [oracle/docker-images#698]
ISSUE in OracleDatabase docker file(s) 

I have been trying to add my own java jar(s) by using loadjava utility but as soon as I use loadjava utility   I get error as below. This error is coming in 12.1 as well as 12.2 containers.

```
Exception in thread "main" java.lang.NoClassDefFoundError: oracle/jdbc/driver/Orr
acleDriver
        at oracle.aurora.server.tools.loadjava.DatabaseOptions.connect(DatabaseOO
ptions.java:116)
        at oracle.aurora.server.tools.loadjava.LoadJavaState.getConnection(LoadJJ
avaState.java:419)
        at oracle.aurora.server.tools.loadjava.LoadJavaState.oracleScriptSet(Loaa
dJavaState.java:1108)
        at oracle.aurora.server.tools.loadjava.SchemaObject.doCreate(SchemaObjecc
t.java:194)
        at oracle.aurora.server.tools.loadjava.SchemaObject.process1(SchemaObjecc
t.java:244)
        at oracle.aurora.server.tools.loadjava.LoadJava.add(LoadJava.java:556)
        at oracle.aurora.server.tools.loadjava.LoadJava.addObject(LoadJava.java::
535)
        at oracle.aurora.server.tools.loadjava.LoadJava.add(LoadJava.java:474)
        at oracle.aurora.server.tools.loadjava.LoadJava.add(LoadJava.java:403)
        at oracle.aurora.server.tools.loadjava.LoadJava.addJar(LoadJava.java:8800
)
        at oracle.aurora.server.tools.loadjava.LoadJava.add(LoadJava.java:456)
        at oracle.aurora.server.tools.loadjava.LoadJava.add(LoadJava.java:403)
        at oracle.aurora.server.tools.loadjava.LoadJava.add(LoadJava.java:372)
```

My same loadjava is working in an oracle instance which is created manually on some linux machine

**Comment by gvenzl** [comment]
Hi @mehtaanshul22,

The exception `Exception in thread "main" java.lang.NoClassDefFoundError: oracle/jdbc/driver/Orr
acleDriver` suggests that the Oracle JDBC driver isn't in the class path when you call the utility, which is true because all client drivers have been removed inside the image to save space, thinking that users should never log into the container and execute a command inside the container.

Can you please try to use the `DBMS_JAVA.LOADJAVA()` method instead calling the `loadjava` tool on the command line. According to the [documentation it should be identical](https://docs.oracle.com/en/database/oracle/oracle-database/12.2/jjdev/loadjava-tool.html#GUID-033299E6-07E2-4C2C-9E26-A2FE25118F1C) but I think that this one doesn't need the JDBC driver to be present:

[DBMS_JAVA Package Documentation:](https://docs.oracle.com/en/database/oracle/oracle-database/12.2/jjdev/DBMS-JAVA-package.html#GUID-1CA4EAD4-CA13-4B98-928D-0A9A9769537B)
> Do not specify the -thin, -oci, -user, and -password options, because they relate to the database connection.

**Comment by mehtaanshul22** [comment]
Hi @gvenzl,

Thanks for your response. As you have mentioned to use DBMS_JAVA.LOADJAVA() method, I think this method cannot be used commandline (Correct me if I am wrong). However my requirement is that I have an application that comprises of many jar files that we load and resolve in the database from command line via some installation scripts.

Another point that you have mentioned is removal of 'all client drivers' from this image in order to save space. Is there a way I can add these drivers and somehow customize my container and proceed with my requirements. I would appreciate if you could give some work around on this.

Thanks in advance

**Comment by marcelo-ochoa** [comment]
In order to reduce the size of the Database image the directory $ORACLE_HOME/jdbc was removed.
Try adding to your script this, 12cR2 version:
```
[oracle@test_env ~]$ mkdir -p $ORACLE_HOME/jdbc/lib/
[oracle@test_env ~]$ ln -s $ORACLE_HOME/inventory/Scripts/ext/jlib/ojdbc8.jar $ORACLE_HOME/jdbc/lib/ojdbc8.jar
```
for 12cR1 try this:
```
[oracle@test_env ~]$ mkdir -p $ORACLE_HOME/jdbc/lib/
[oracle@test_env ~]$ ln -s $ORACLE_HOME/inventory/Scripts/ext/jlib/ojdbc6.jar $ORACLE_HOME/jdbc/lib/ojdbc6.jar
```
after that a simple test like this:
```
[oracle@test_env ~]$ loadjava -t -u scott/tiger@pdb1 $ORACLE_HOME/rdbms/jlib/CDC.jar 
SQL Error while connecting with thin driver to pdb1: IO Error: could not resolve the connect identifier  "pdb1"
```
means that the JDBC driver is found and loadjava is try to connect to a PDB.
HTH, Marcelo.

**Comment by gvenzl** [comment]
The JDBC driver is now part of the image, the `loadjava` utility should work fine.
