### ISSUE TITLE
What's the difference between this image and the one on docker store?

### ISSUE THREAD

**Issue by zymzxq** [oracle/docker-images#704]
https://store.docker.com/images/oracle-database-enterprise-edition

**Comment by vipinponnarath** [comment]
One difference I spotted is that the one on docker store doesnt have the post setup and post startup scripts option, though this would be a nice one to have. The slim version on the docker store is what I was trying with.

**Comment by Djelibeybi** [comment]
This is something @gvenzl should answer, but yes there is a difference between the image on the Oracle Container Registry & Docker Store and the one published here on GitHub.

**Comment by whisdom** [comment]
There are the following obvious differences:
 - The prebuild image in the docker store is Enterprise Edition only. The scripts here in Github allow to create images for Standard Edition also.
 - The prebuild image cannot be patched. This is mentioned in the setup instructions. The scripts here in Github allow to create patches images also.
 - The prebuild image is much smaller. The Slim image is about 2.44 GB, the EE image create by the scripts here in Github will be about 15GB. this is because the scripts perform a normal installation of the Oracle Database software. The prebuild image from the store contains a subset (e.g. the OPatch directory is missing).
There can be more differences, but these can be listed quite easily.

**Comment by gvenzl** [comment]
@whisdom is quite spot on. The differences are all documented with the images on the Docker Store where you can obtain those images.

Furthermore, the images here on GitHub tend to be slightly ahead to those on the store due to the participation of the community. For example, the images on GitHub have ways to let you run scripts after database setup and/or database startup, making it easier to create schemas or run startup scripts. They also try to detect as many wrong configuration issues ahead of time.

All in all, they pursue two different goals: 
* The prebuilt images try to be as **small and quick** as possible
* The ones on GitHub try to be as **general purpose** as possible. This is done so that folks can go ahead, fork this repo and amend the build files to their needs.

One note on the 15GB image size. This is mainly due to the fact that you build your own image and the way how Docker and the layered filesystem work. You can easily shrink the size by half by just using the `--squash` option or export/import the image. See https://geraldonit.com/2017/11/13/how-to-create-small-docker-images/ for more information on that.
