### ISSUE TITLE
Remote Database with oracle/fmw-infrastructure:12.2.1.3

### ISSUE THREAD

**Issue by dvbencomo** [oracle/docker-images#705]
Hello, 

when trying to run the docker image with a remote database, I always get the error:

>Loading SOA RCU into database
>RCU has some error
>RCU Loading Failed .. Please check the RCU logs

question: how should I run the image with a local database? This is an 11g version.

Thanks.

**Comment by mriccell** [comment]
@dvbencomo are you able to run the image with the DB running in a container following the instructions at https://github.com/mriccell/docker-images/tree/master/OracleFMWInfrastructure?
If you want to use your local DB you need to add the connection information needed for the Datasource in the https://github.com/mriccell/docker-images/blob/master/OracleFMWInfrastructure/dockerfiles/12.2.1.3/infraDomain.env.list file.  
The best is enter the DB information necessary to build the data source URL, username, and password in the infraDomain.env.list file build the image and try docker run from the image and take a look at the Data source and adjust the information so that it can connect to the db.

**Comment by mriccell** [comment]
Closing due to lack of feedback.
