### ISSUE TITLE
OBIEE 12.2.1.3: cannot connect to oracle database 11g xe

### ISSUE THREAD

**Issue by srgykim** [oracle/docker-images#752]
Hi! I can't run docker container with OBIEE. I use this command to run it:

```
docker run -it -p 9500:9500 -p 9502:9502 -e ADMIN_USERNAME=weblogic -e ADMIN_PASSWORD=weblogic01 -e DB_HOST=localhost -e DB_PORT=1521 -e DB_SERVICE=xe -e DB_USERNAME=sys -e DB_PASSWORD=oracle -e SCHEMA_PREFIX=DEV -e SCHEMA_PASSWORD=oracle oracle/biplatform:12.2.1.3
```

But, I get this error:

```
Starting Fusion Middleware Configuration Wizard for BIEE
ORACLE_HOME set as /u01/oracle
BI_PRODUCT_HOME set as /u01/oracle/bi
PATH set as /u01/oracle/bi/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/java/default/bin:/u01/oracle/oracle_common/common/bin:/u01/oracle/wlserver/common/bin:/u01/oracle/container-scripts
LD_LIBRARY_PATH set as /u01/oracle/bi/lib
INSTALL_PROPERTIES /u01/oracle/bi/../oui/mw/bi/metadata/config.properties
INSTALL_INVOCATION /u01/oracle/bi/bin/../../oui/bin/launch.sh -clone ORACLE_HOME=/u01/oracle -invPtrLoc /u01/oracle/oraInst.loc -ignoreSysPrereqs -silent -responseFile /tmp/create_domain_lEzYQLAiCZ/response.txt -J-Doracle.as.install.engine.weblogic.config.mode=true -J-Doracle.config.mode=true -J-Doracle.as.install.engine.install.properties.location=/u01/oracle/bi/../oui/mw/bi/metadata/config.properties -J-DSHIPHOME_STAGE_DIR=/u01/oracle/bi/../oui/mw/bi -paramfile /tmp/XXX-2606169262.1
Launcher log file is /tmp/OraInstall2018-02-11_03-41-05PM/launcher2018-02-11_03-41-05PM.log.
Checking swap space: must be greater than 500 MB.   Actual 3994 MB    Passed
Checking if this platform requires a 64-bit JVM.   Actual 64    Passed
Log: /u01/oracle/.inventory/logs/install2018-02-11_03-41-05PM.log
Copyright (c) 1999, 2017, Oracle and/or its affiliates. All rights reserved.
Reading response file..
Verifying data
[VALIDATION] [ERROR]:Error connecting to 'Oracle database at host localhost port 1521 service name xe' - Listener could be down
[VALIDATION] [SUGGESTION]:Make sure the database is up and running and connect string, user name and password are correct.
configuration Failed. Exiting configuration due to data validation failure.

The log(s) can be found here: /tmp/OraInstall2018-02-11_03-41-05PM.
/u01/createAndStartDomain.sh: line 203: /u01/oracle/user_projects/domains/bi/domainready.txt: No such file or directory
```

**Comment by sjvp** [comment]
Oracle Database Express Edition is not supported by Oracle Business Intelligence Enterprise Edition 12c.

This is as per http://www.oracle.com/technetwork/middleware/ias/downloads/fusion-certification-100350.html.  See the 12.2.1.3 xlsx, "Database" sheet rows for "Oracle Business Intelligence Enterprise Edition" "Target DB for RCU".

The createAndStartDomain.sh and wait_for_db.sh scripts are hardcoded to Oracle Database, but the public tools invoked will also support DB/2 and SQL Server if you edit the shell scripts appropriately.

**Comment by Djelibeybi** [comment]
That command wouldn't work either, because OBIEE would be looking for Oracle XE inside the _same_ container (`DB_HOST=localhost`) which is invalid. You need to point OBIEE at _another_ container running Oracle Database.

**Comment by srgykim** [comment]
But I have a container with Oracle Database and connected to it through SQL developer on localhost. So, now if I install Oracle DB EE, what do I need to specify at **DB_HOST**? I want to run everything on Mac OS X.

**Comment by Djelibeybi** [comment]
SQL Developer is running on the Mac, and the container is exposing its port to the Mac. To link two containers together, you need to use either the `--link` parameter or use the same Docker network for both and then refer to the container name, not `localhost`.

**Comment by sjvp** [comment]
You have a couple of choices:

- If you have started the DB container with a port published on the host (-p or -P), then use the host's name, e.g.

  -e DB_HOST=$(hostname -f) 

Having said that, I don't know if the above is true on Mac, where you are running docker in a separate hidden VM.

- or you can wire the containers together using formal docker mechanisms, as per https://github.com/oracle/docker-images/tree/master/OracleBI#using-a-database-container, e.g.
 
  --link db:db -e DB_HOST=db

I don't which, if any, of the user-defined network options would work on Mac - but the problem is generic and not specific to OBIEE.

**Comment by cbosepandian** [comment]
Hi srgykim,
Still you are considering using oracle XE with OBIEE 12c, the following option will work out
1. Instead of create repository command, Go with Generate script to first generate db script with your xe connection details
2. while generate script, use will two or three components as XE is capable of doing only two or three at a time.
3. After script generated, You will get systemload.sql, postload sql files. Using it, create schemas directly in your server.

google it. you will get the scripts for that.
Hope it will help!

But I would recommend this installation with XE only for learning purpose. if you are going to use it for business, XE is not good choice and not supported by oracle to in support matrix.
