### ISSUE TITLE
server jre image for arm

### ISSUE THREAD

**Issue by PeterJakubik** [oracle/docker-images#820]
Hello
I'm running Linux on arm (Raspbian/Tinker Os)
Running `uname -m` gives me armv71

After pulling store/oracle/serverjre 
`docker pull store/oracle/serverjre:8` 

I got an error:
`standard_init_linux.go:190: exec user process caused "exec format error"`

Quick check `docker image inspect` revealed that images is for architecture "amd64" and not arm

Do you also plan to support arm docker images?

I'm not a docker expert, but why is the amd64 image pulled for arm architecture?

Thank you
Peter

**Comment by Djelibeybi** [comment]
All the Docker Store images provided by Oracle are for AMD64 only, because that's currently the only supported Docker platform that's certified by those products.

However, we have recently released a developer preview build of Oracle Linux for ARM64: https://blogs.oracle.com/linux/announcing-oracle-linux-7-for-arm

And even more recently, we shipped a preview build of Oracle Container Runtime for Docker for ARM64, along with official images of `oraclelinux` for ARM64: https://blogs.oracle.com/linux/oracle-container-runtime-for-docker-on-oracle-linux-for-arm64

I suspect we might see some Dockerfiles arrive on this repo that would build on ARM64, but I wouldn't expect binary images on the Oracle Container Registry or Docker Store any time soon.

**Comment by PeterJakubik** [comment]
For Info. As of March 2018 Raspbian is 32 bit OS (IMHO sane choice on such a constrained device) and therefore ARM64 docker images wouldn't work.

`docker pull oraclelinux:7-slim` on raspbian gives: no matching manifest for linux/arm

**Comment by Djelibeybi** [comment]
Correct. We've only released `oraclelinux` images for ARM64. You need a 64-bit OS on your Raspberry Pi, like Oracle Linux 7: https://blogs.oracle.com/wim/raspberry-pi-3-b-oracle-linux-74-arm64-with-uek5-preview-image-available-for-download

We just pushed a new image that includes UEK5 which will allow our build of `docker-engine` to run.,
