### ISSUE TITLE
Docker RAC / Add racnode3 failing

### ISSUE THREAD

**Issue by largefp2018** [oracle/docker-images#841]
04-11-2018 04:31:16 UTC :  : Cluster Nodes are racnode1 racnode2 racnode3
04-11-2018 04:31:16 UTC :  : Running SSH setup for grid user between nodes racnode1 racnode2 racnode3
04-11-2018 04:32:03 UTC :  : Running SSH setup for oracle user between nodes racnode1 racnode2 racnode3
04-11-2018 04:32:35 UTC :  : Checking Cluster Status on racnode1
04-11-2018 04:32:35 UTC :  : Checking Cluster
04-11-2018 04:32:35 UTC : : Cluster Check on remote node failed
04-11-2018 04:32:35 UTC : : Error has occurred in Grid Setup, Please verify!

**Comment by psaini79** [comment]
Hi,

It seems SSH setup between the nodes has failed. Since we do not control password policy of user environment, please make sure the grid and oracle user password is same when you add node on all the existing nodes. Once the node addition is done, you can change the password on every node or maintain it according to your password policy.

For details, please refer https://github.com/oracle/docker-images/blob/master/OracleDatabase/RAC/OracleRealApplicationClusters/README.md.

It is mentioned in the README.md:
OS_PASSWORD=You need to pass this for ssh setup between grid and oracle user. OS_PASSWORD will rest the password of grid and Oracle user based on your env. You need common password on all the containers during Node Addition. Once the Node Addition is done you can change the passwords based on your environment policies.

Let me know if you face any issue. I will look into it.

**Comment by largefp2018** [comment]
Hi,
     This issue was resolved as your help.
Thanks.
