### ISSUE TITLE
Volumes for scripts/startup & scripts/setup not present Docker files

### ISSUE THREAD

**Issue by jimzucker** [oracle/docker-images#878]
The directories are missing in the docker compose and the volumes are missing for;
   -v /opt/oracle/scripts/startup | /docker-entrypoint-initdb.d/startup
   -v /opt/oracle/scripts/setup | /docker-entrypoint-initdb.d/setup

==============================================================

The README.md documents these 4 mount points

   -v /opt/oracle/scripts/startup | /docker-entrypoint-initdb.d/startup
                  Optional: A volume with custom scripts to be run after database startup.
                  For further details see the "Running scripts after setup and on startup" section below.
   -v /opt/oracle/scripts/setup | /docker-entrypoint-initdb.d/setup
                  Optional: A volume with custom scripts to be run after database setup.
                  For further details see the "Running scripts after setup and on startup" section below.

#But in the current image they are not available and directories are not created.

➜  12.1.0.2 git:(oracle_ci) ✗ egrep VOL Dockerfile.*
Dockerfile.ee:VOLUME ["$ORACLE_BASE/oradata"]
Dockerfile.se2:VOLUME ["$ORACLE_BASE/oradata"]

#The scripts reference them
runOracle.sh:  # Execute custom provided startup scripts

➜  12.1.0.2 git:(oracle_ci) ✗ egrep 'setup' *.sh
runOracle.sh:  # Execute custom provided setup scripts
runOracle.sh:  $ORACLE_BASE/$USER_SCRIPTS_FILE $ORACLE_BASE/scripts/setup
setupLinuxEnv.sh:mkdir -p $ORACLE_BASE/scripts/setup && \

#there is a link created as described
➜  12.1.0.2 git:(oracle_ci) ✗ egrep docker-entrypoint-initdb.d *.sh
setupLinuxEnv.sh:ln -s $ORACLE_BASE/scripts /docker-entrypoint-initdb.d && \

**Comment by gvenzl** [comment]
Hi @jimzucker,

We deliberately don't expose those via the `VOLUME` instruction as not everybody may want to use them or, for example, just mount one volume to `$ORACLE_BASE/scripts` instead of two.

Another issue with volumes is that you cannot get rid of them when extending an image, same as ports. We are therefore careful which volumes to expose declaratively.
So far the only one that makes sense is the one for the database data files itself and even there people struggle with the issue that if they ever want to build an image that includes the database inside the image, they have to amend the dockerfile itself and build an entire new image rather than just extend the image and remove the volume (see #478)

**Comment by jimzucker** [comment]
@gvenzl OK, I see. How about we amend the README with a AWARENESS ITEM, that you have to extend the image to make those available, it might be there but I missed it. The features are great, just takes some time to find them.

**Comment by jimzucker** [comment]
Happy to take a shot at amending them if you like..

**Comment by gvenzl** [comment]
It's not so much that people have to extend the image to get the volumes exposed. `-v` will quite happily expose anything inside a container even if it isn't specifically exposed via the `VOLUME` instruction.

Fair enough, do you think that the paragraph [Running scripts after setup and on startup](https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance#running-scripts-after-setup-and-on-startup) is not clear enough then, or too far down the ReadMe?

**Comment by gvenzl** [comment]
Closing due to lack of response.

**Comment by jimzucker** [comment]
@gvenzl  Thanks I was able to get our CI up and running 100% with your advice
