### ISSUE TITLE
Bind volume permissions issue

### ISSUE THREAD

**Issue by lkiii** [oracle/docker-images#913]
Hello,

I am having issue with oracle database and startup scripts, I have 
```
  volumes:
        - ./db/oracleDump:/docker-entrypoint-initdb.d/startup

```

And the issue is that `ls -la /opt/oracle/scripts/startup/` shows that all files inside the folder are owned by root. 
```
drwxr-xr-x 2 root   root       4096 Jun 26 09:41 .
drwxr-xr-x 4 oracle dba        4096 Jun 25 06:44 ..
-rwxr-xr-x 1 root   root         25 Jun 26 09:41 .gitignore
-rwxr-xr-x 1 root   root 7577051136 Jun 13 08:10 dump.dmp
-rwxr-xr-x 1 root   root        195 Jun 27 08:27 start.sh
```
So launching it is impossible, Had anyone solved issue like this?

I have tried `chown -R oracle /opt/oracle/scripts/startup/` inside the container, but it does not affect owership of the files inside.

Thank you for your help in advance.

**Comment by gvenzl** [comment]
Hi @lkiii,

What's the error that you are getting? All the files have the `read` and `execute` flags set for the `others` group so the container should be able to execute them just fine.

**Comment by lkiii** [comment]
I have start.sh with
```
impdp "'"/ as sysdba"'" schemas=mro,ramco,biotime,navision,loc,fltsql_read,fin_read,middleware,flt_read,reports,quantum directory=/opt/oracle/scripts/startup/ dumpfile=dump.dmp
```

dump.dmp is in the same directory and when I run it I get
```
Connected to: Oracle Database 12c Standard Edition Release 12.2.0.1.0 - 64bit Production
ORA-39002: invalid operation
ORA-39070: Unable to open the log file.
ORA-39087: directory name /OPT/ORACLE/SCRIPTS/STARTUP/ is invalid
```

Another issue is that this script is not being triggered during the startup of the container.

**Comment by gvenzl** [comment]
Hi @lkiii,

Thanks a lot for the additional information, that helps solve the mystery.

The issue you are facing is I believe misunderstanding on how directories work in Oracle. The database has the concept of [DIRECTORY data dictionary objects](https://docs.oracle.com/en/database/oracle/oracle-database/18/sqlrf/CREATE-DIRECTORY.html#GUID-8E9C569A-1B06-42C4-9586-0EF83437001A) that can be granted to the appropriate users and so forth, rather than just being exposed directly to the file system via a path.

When you invoked `impdp` with `directory=/opt/oracle/scripts/startup/` the database is actually looking for a DIRECTORY data dictionary object with the name `/OPT/ORACLE/SCRIPTS/STARTUP/` rather than just a location on the file system. However, the object does not exist, which is the reason why you are getting `ORA-39087: directory name /OPT/ORACLE/SCRIPTS/STARTUP/ is invalid`

In order for you to import the data you will have to connect as `SYS` (or `/ as sysdba` as you are already doing in `impdp` as well) and issue:

```sql
CREATE DIRECTORY MY_IMPORT_DIR AS '/opt/oracle/scripts/startup';
```

to create a new directory object `MY_IMPORT_DIR` (replace the name as you see fit) and then issue the `impdp` command referencing this directory:

```
impdp "'"/ as sysdba"'" schemas=schema1,schema2,etc directory=MY_IMPORT_DIR dumpfile=dump.dmp
```

Hope this helps!

Thx,

**Comment by lkiii** [comment]
Thank you I will try the solution. I will let you know about the outcome.

**Comment by lkiii** [comment]
I have also another issue that startup script is not being executed during launch. As I understood starting container should execute `*.sh` located in `/docker-entrypoint-initdb.d/startup`?

**Comment by gvenzl** [comment]
Yes, either `/docker-entrypoint-initdb.d/startup` or `/opt/oracle/scripts/startup`. `/docker-entrypoint-initdb.d` is actually just a symbolic link to `/opt/oracle/scripts` (see [setupLinux.sh](https://github.com/oracle/docker-images/blob/master/OracleDatabase/SingleInstance/dockerfiles/12.2.0.1/setupLinuxEnv.sh#L18)).

You should see a line similar to this:

```
Executing user defined scripts
/opt/oracle/runOracle.sh: running /opt/oracle/scripts/setup/01_shellExample.sh
Environment: Linux 51f09a648c8e 4.1.12-94.3.8.el7uek.x86_64 #2 SMP Fri Jun 30 10:40:13 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by lkiii** [comment]
Thank you for the clarification, but I have no clue why my script is not being launched.

I have this line in my logs, maybe it stops execution of all startup scripts?  `/opt/oracle/checkDBStatus.sh: line 27: sqlplus: command not found`-

**Comment by gvenzl** [comment]
Yes, that could be the reason. Did you change anything else besides `createAsContainerDatabase=false` when building the image?

**Comment by gvenzl** [comment]
Closing due to lack of response. Please reopen if needed.
