### ISSUE TITLE
Memory sizing not optimal on large servers

### ISSUE THREAD

**Issue by samuelvetsch** [oracle/docker-images#920]
I'm currently trying to setup the Oracle Database SingleInstance 12.1.x image for a CI/CD server.
It is a CentOS server with 32 CPUs and 250 GB of memory.
We need multiple database instances for each branch.

The image creation is ok and I can use the database. But as soon as I try to limit the memory (to 5GB) of the docker container I run into issues with same kind of error than:

https://github.com/oracle/docker-images/issues/307

The database only works when no memory limitation is set.
I found a workaround by adding an ENV ORACLE_MEMORY variable and removing the code from createDB.sh:
````
if [ `nproc` -gt 8 ]; then
    sed -i -e 's|TOTALMEMORY = "2048"||g' $ORACLE_BASE/dbca.rsp
fi;
````

This code is removing the 2GB memory limit on servers with more than 8 cpus (my case). Without this memory limit, my instance is consuming around 80 GB !! of memory just for a single container...

When setting, the dbca.rsp memory limit to 5GB for example, everything works fine with memory limtation on the container.
Would it be possible to add a parameter allowing to select the memory strategy ?

**Comment by gvenzl** [comment]
Hi @samuelvetsch, I'm confuse about the 5GB. At the top you say 5GB made you run into similar issues at #307 but at the bottom you say that 5GB worked fine?

You can override the memory requirements by editing the `dbca.rsp.tmpl` file. The `sed` command will only replace the `TOTALMEMORY = "2048"` line but if the line happens to be `TOTALMEMORY=" 5120" it won't take any affect.

Also note that this is only used for database creation time. Once the database is up and running , you can and will have to set the database parameters accordingly `SGA_MAX_SIZE`, `SGA_TARGET`, `PGA_AGGREGATE_LIMIT`, `PGA_AGGREGATE_TARGET`.

**Comment by samuelvetsch** [comment]
Hi, the trigger is not around 5GB, that was just my target memory size example. The trigger was about the number of CPU.
In my tests, once db created and started with full memory (250GB), I was not able to restart the DB with less than 15GB using docker memory limits. But I did not play with the SGA_MAX_SIZE, SGA_TARGET, PGA_AGGREGATE_LIMIT, PGA_AGGREGATE_TARGET.

I would just suggest to make this TOTALMEMORY an ENV or ARG parameter in order to let user define manually this size.

**Comment by gvenzl** [comment]
Once the database is created, passing on an environment variable won't help either anymore as the memory requirements are specified as a database parameter. So let's say you create a new database container, store the database in a volume (as one should), throw the container away and recreate a new container, the TOTALMEMORY won't have any affect anymore as the database is already created. At that point the user has to configure `SGA_TARGET` and `PGA_AGGREGATE_TARGET` accordingly for what he wants.

If totalmemory is not specified, the installer itself will take 40% of the total memory available. So if you were to create a new container with Docker memory limits in place, the memory consumption is already adjusted accordingly by the installer itself if you happen to run on 8 CPUs and more.
Otherwise, it will run with as little memory as Oracle recommends, which happens to be 2GB. One can increase that after database setup as well, if wanted.

**Comment by dbeaulieu1** [comment]
I have the same error, but I don't want to increase Oracle memory. In fact, I run on AKS with servers gt than 8 cpus to be able to run many Oracle containers. I want to run multiple pods of my Oracle container, as low memory as possible. If I set CPU_COUNT less than 8, and > 0 (of course) at installation, I think that Oracle should be able to start with 2048m of memory.

Am I correct ?
